import { useEffect, useMemo, useState, type FormEvent } from "react";
import { BarChart3, KeyRound, Megaphone, MessageSquareText, Plus, RefreshCw, Send, UserPlus, Users } from "lucide-react";
import { apiRequest } from "../lib/api";
import { sanitizePhoneInput } from "../lib/contact";

type Customer = { id: number; company_name: string; contact_name: string; email: string; phone: string; status: string; campaign_count: number; spend: number; revenue: number };
type Campaign = { id: number; customer_id: number; name: string; platform: string; status: string; monthly_budget: number; management_fee: number; start_date: string };
type Ticket = { id: number; company_name: string; subject: string; message: string; status: string; priority: string; admin_reply: string };
type Request = { id: number; company_name: string; service: string; details: string; status: string };
type AdminData = { customers: Customer[]; campaigns: Campaign[]; stats: unknown[]; tickets: Ticket[]; serviceRequests: Request[] };

const fieldClass = "mt-1 w-full rounded-xl border border-white/15 bg-black/35 px-3 py-2.5 text-[12px] font-bold text-white outline-none focus:border-[#00a8c4]";
const labelClass = "text-[10px] font-black uppercase tracking-wide text-white/50";
const money = (value: number) => new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY", maximumFractionDigits: 0 }).format(Number(value || 0));

export function AdminCustomerPanel() {
  const [data, setData] = useState<AdminData | null>(null);
  const [notice, setNotice] = useState("");
  const [customerForm, setCustomerForm] = useState({ companyName: "", contactName: "", email: "", phone: "", password: "" });
  const [campaignForm, setCampaignForm] = useState({ customerId: "", name: "", platform: "google", monthlyBudget: "5000", managementFee: "0", startDate: new Date().toISOString().slice(0, 10) });
  const [statsForm, setStatsForm] = useState({ campaignId: "", periodStart: new Date().toISOString().slice(0, 8) + "01", periodEnd: new Date().toISOString().slice(0, 10), spend: "", impressions: "", clicks: "", leads: "", conversions: "", revenue: "" });
  const [reply, setReply] = useState<Record<number, string>>({});

  const load = async () => { try { setData(await apiRequest<AdminData>("/api/admin/customers")); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : "Müşteriler yüklenemedi."); } };
  useEffect(() => { void load(); }, []);
  const campaignsByCustomer = useMemo(() => new Map((data?.customers || []).map((customer) => [customer.id, (data?.campaigns || []).filter((campaign) => campaign.customer_id === customer.id)])), [data]);

  const createCustomer = async (event: FormEvent) => { event.preventDefault(); try { await apiRequest("/api/admin/customers", { method: "POST", body: JSON.stringify(customerForm) }); setCustomerForm({ companyName: "", contactName: "", email: "", phone: "", password: "" }); setNotice("Müşteri hesabı oluşturuldu."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Hesap oluşturulamadı."); } };
  const createCampaign = async (event: FormEvent) => { event.preventDefault(); try { await apiRequest("/api/admin/campaigns", { method: "POST", body: JSON.stringify({ ...campaignForm, customerId: Number(campaignForm.customerId), monthlyBudget: Number(campaignForm.monthlyBudget), managementFee: Number(campaignForm.managementFee) }) }); setNotice("Kampanya müşteriye bağlandı."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Kampanya eklenemedi."); } };
  const saveStats = async (event: FormEvent) => { event.preventDefault(); try { const { campaignId, ...payload } = statsForm; await apiRequest(`/api/admin/campaigns/${campaignId}/stats`, { method: "POST", body: JSON.stringify(payload) }); setNotice("Reklam performans raporu güncellendi."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Rapor kaydedilemedi."); } };
  const answerTicket = async (ticket: Ticket) => { try { await apiRequest(`/api/admin/tickets/${ticket.id}`, { method: "PATCH", body: JSON.stringify({ status: "answered", adminReply: reply[ticket.id] ?? ticket.admin_reply }) }); setNotice("Müşteri mesajı yanıtlandı."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Yanıt kaydedilemedi."); } };
  const updateRequest = async (item: Request, status: string) => { await apiRequest(`/api/admin/service-requests/${item.id}`, { method: "PATCH", body: JSON.stringify({ status }) }); await load(); };

  return (
    <div className="mt-8 space-y-7">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#3ec8dc]">Müşteri operasyon merkezi</p><h2 className="mt-2 text-[26px] font-black">Reklam müşterileri ve performans paneli</h2><p className="mt-2 text-[12px] text-white/55">Hesap açın, reklam bütçesini tanımlayın, Google/Meta sonuçlarını girin ve müşteri taleplerini yönetin.</p></div><button onClick={() => void load()} className="flex items-center gap-2 rounded-xl border border-white/15 px-3 py-2 text-[11px] font-black text-white/70"><RefreshCw className="h-4 w-4" /> Yenile</button></div>
      {notice && <p className="rounded-xl border border-cyan-300/20 bg-cyan-300/10 px-4 py-3 text-[11px] font-bold text-cyan-100">{notice}</p>}

      <div className="grid gap-5 xl:grid-cols-3">
        <form onSubmit={createCustomer} className="rounded-[24px] border border-white/10 bg-[#18181f] p-5"><UserPlus className="h-5 w-5 text-[#3ec8dc]" /><h3 className="mt-4 text-[18px] font-black">Müşteri hesabı aç</h3><div className="mt-5 grid gap-3">{[["Firma", "companyName"], ["Yetkili", "contactName"], ["E-posta", "email"], ["Telefon", "phone"], ["Geçici şifre", "password"]].map(([label, key]) => <label key={key} className={labelClass}>{label}<input required={key !== "phone"} maxLength={key === "phone" ? 14 : 80} type={key === "password" ? "password" : key === "email" ? "email" : key === "phone" ? "tel" : "text"} inputMode={key === "phone" ? "numeric" : undefined} value={customerForm[key as keyof typeof customerForm]} onChange={(event) => setCustomerForm({ ...customerForm, [key]: key === "phone" ? sanitizePhoneInput(event.target.value) : event.target.value })} className={fieldClass} /></label>)}</div><button className="mt-4 flex items-center gap-2 rounded-xl bg-[#00a8c4] px-4 py-2.5 text-[11px] font-black"><Plus className="h-4 w-4" /> Hesabı oluştur</button></form>

        <form onSubmit={createCampaign} className="rounded-[24px] border border-white/10 bg-[#18181f] p-5"><Megaphone className="h-5 w-5 text-[#a5b4fc]" /><h3 className="mt-4 text-[18px] font-black">Kampanya ve bütçe ekle</h3><label className={`${labelClass} mt-5 block`}>Müşteri<select required value={campaignForm.customerId} onChange={(event) => setCampaignForm({ ...campaignForm, customerId: event.target.value })} className={fieldClass}><option value="">Seçin</option>{data?.customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.company_name}</option>)}</select></label><label className={`${labelClass} mt-3 block`}>Kampanya adı<input required value={campaignForm.name} onChange={(event) => setCampaignForm({ ...campaignForm, name: event.target.value })} className={fieldClass} /></label><div className="mt-3 grid grid-cols-2 gap-3"><label className={labelClass}>Platform<select value={campaignForm.platform} onChange={(event) => setCampaignForm({ ...campaignForm, platform: event.target.value })} className={fieldClass}><option value="google">Google</option><option value="meta">Meta</option><option value="other">Diğer</option></select></label><label className={labelClass}>Başlangıç<input type="date" value={campaignForm.startDate} onChange={(event) => setCampaignForm({ ...campaignForm, startDate: event.target.value })} className={fieldClass} /></label><label className={labelClass}>Aylık bütçe<input type="number" value={campaignForm.monthlyBudget} onChange={(event) => setCampaignForm({ ...campaignForm, monthlyBudget: event.target.value })} className={fieldClass} /></label><label className={labelClass}>Yönetim ücreti<input type="number" value={campaignForm.managementFee} onChange={(event) => setCampaignForm({ ...campaignForm, managementFee: event.target.value })} className={fieldClass} /></label></div><button className="mt-4 flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-2.5 text-[11px] font-black"><Plus className="h-4 w-4" /> Kampanyayı bağla</button></form>

        <form onSubmit={saveStats} className="rounded-[24px] border border-white/10 bg-[#18181f] p-5"><BarChart3 className="h-5 w-5 text-[#6ee7b7]" /><h3 className="mt-4 text-[18px] font-black">Aylık rapor gir</h3><label className={`${labelClass} mt-5 block`}>Kampanya<select required value={statsForm.campaignId} onChange={(event) => setStatsForm({ ...statsForm, campaignId: event.target.value })} className={fieldClass}><option value="">Seçin</option>{data?.campaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</select></label><div className="mt-3 grid grid-cols-2 gap-3">{[["Dönem başlangıç", "periodStart", "date"], ["Dönem bitiş", "periodEnd", "date"], ["Harcama", "spend", "number"], ["Ölçülen gelir", "revenue", "number"], ["Gösterim", "impressions", "number"], ["Tıklama", "clicks", "number"], ["Lead", "leads", "number"], ["Dönüşüm", "conversions", "number"]].map(([label, key, type]) => <label key={key} className={labelClass}>{label}<input required type={type} value={statsForm[key as keyof typeof statsForm]} onChange={(event) => setStatsForm({ ...statsForm, [key]: event.target.value })} className={fieldClass} /></label>)}</div><button className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2.5 text-[11px] font-black"><BarChart3 className="h-4 w-4" /> Raporu kaydet</button></form>
      </div>

      <section><div className="flex items-center gap-2"><Users className="h-5 w-5 text-[#3ec8dc]" /><h3 className="text-[19px] font-black">Müşteri hesapları</h3></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{data?.customers.map((customer) => <article key={customer.id} className="rounded-2xl border border-white/10 bg-[#18181f] p-4"><div className="flex items-start justify-between"><div><p className="text-[14px] font-black">{customer.company_name}</p><p className="mt-1 text-[10px] text-white/45">{customer.contact_name} · {customer.email}</p></div><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[8px] font-black text-emerald-300">{customer.status}</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[["Kampanya", customer.campaign_count], ["Harcama", money(customer.spend)], ["Gelir", money(customer.revenue)]].map(([label, value]) => <div key={label} className="rounded-xl bg-black/25 p-3"><p className="text-[8px] text-white/40">{label}</p><p className="mt-1 text-[11px] font-black">{value}</p></div>)}</div><div className="mt-3 flex flex-wrap gap-1.5">{(campaignsByCustomer.get(customer.id) || []).map((campaign) => <span key={campaign.id} className="rounded-full border border-white/10 px-2 py-1 text-[8px] font-bold text-white/55">{campaign.platform} · {campaign.name}</span>)}</div></article>)}</div></section>

      <div className="grid gap-5 xl:grid-cols-2"><section><div className="flex items-center gap-2"><MessageSquareText className="h-5 w-5 text-[#3ec8dc]" /><h3 className="text-[19px] font-black">Destek mesajları</h3></div><div className="mt-4 space-y-3">{data?.tickets.map((ticket) => <article key={ticket.id} className="rounded-2xl border border-white/10 bg-[#18181f] p-4"><p className="text-[9px] font-black uppercase text-[#3ec8dc]">{ticket.company_name} · {ticket.priority}</p><h4 className="mt-2 text-[13px] font-black">{ticket.subject}</h4><p className="mt-2 text-[10px] leading-relaxed text-white/55">{ticket.message}</p><textarea value={reply[ticket.id] ?? ticket.admin_reply} onChange={(event) => setReply({ ...reply, [ticket.id]: event.target.value })} placeholder="Müşteriye yanıt" rows={3} className={fieldClass} /><button onClick={() => void answerTicket(ticket)} className="mt-2 flex items-center gap-2 rounded-xl bg-[#00a8c4] px-3 py-2 text-[10px] font-black"><Send className="h-3.5 w-3.5" /> Yanıtla</button></article>)}</div></section><section><h3 className="text-[19px] font-black">Yeni hizmet talepleri</h3><div className="mt-4 space-y-3">{data?.serviceRequests.map((item) => <article key={item.id} className="rounded-2xl border border-white/10 bg-[#18181f] p-4"><p className="text-[9px] font-black uppercase text-[#a5b4fc]">{item.company_name}</p><h4 className="mt-2 text-[13px] font-black">{item.service}</h4><p className="mt-2 text-[10px] leading-relaxed text-white/55">{item.details}</p><select value={item.status} onChange={(event) => void updateRequest(item, event.target.value)} className={`${fieldClass} mt-3`}><option value="new">Yeni</option><option value="reviewing">İnceleniyor</option><option value="quoted">Teklif hazır</option><option value="approved">Onaylandı</option><option value="closed">Kapalı</option></select></article>)}</div></section></div>
    </div>
  );
}
