import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, CalendarClock, CircleDollarSign, MessageSquarePlus, Plus, Target, TrendingUp, Users } from "lucide-react";
import { apiRequest } from "../lib/api";

type Stage = "new" | "qualified" | "proposal" | "negotiation" | "won" | "lost";
type Deal = { id:number; company_name:string; contact_name:string; phone:string; service:string; value:number; stage:Stage; probability:number; next_action:string; follow_up_at:string; activity_count:number };
type DealActivity = { id:number; deal_id:number; kind:string; detail:string; created_at:string };
const STAGES:{id:Stage;label:string;color:string}[] = [
  {id:"new",label:"Yeni fırsat",color:"text-sky-200 bg-sky-400/10 border-sky-400/20"},{id:"qualified",label:"Nitelikli",color:"text-cyan-200 bg-cyan-400/10 border-cyan-400/20"},{id:"proposal",label:"Teklif",color:"text-violet-200 bg-violet-400/10 border-violet-400/20"},{id:"negotiation",label:"Görüşme",color:"text-amber-200 bg-amber-400/10 border-amber-400/20"},{id:"won",label:"Kazanıldı",color:"text-emerald-200 bg-emerald-400/10 border-emerald-400/20"},{id:"lost",label:"Kaybedildi",color:"text-slate-400 bg-white/[0.03] border-white/10"},
];
const field="mt-1.5 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-indigo-300/50";
const fresh={companyName:"",contactName:"",phone:"",email:"",service:"Kurumsal web sitesi",value:25000,nextAction:"İlk görüşmeyi planla",followUpAt:"",notes:""};

export function PartnerCrmSection(){
  const [deals,setDeals]=useState<Deal[]>([]),[activities,setActivities]=useState<DealActivity[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[selected,setSelected]=useState<number|null>(null);
  const [activity,setActivity]=useState({kind:"note",detail:""}),[form,setForm]=useState(fresh);
  const load=useCallback(async()=>{try{const data=await apiRequest<{deals:Deal[];activities:DealActivity[]}>("/api/partners/crm/deals");setDeals(data.deals);setActivities(data.activities);}catch(e){setNotice(e instanceof Error?e.message:"CRM yüklenemedi.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const summary=useMemo(()=>{const active=deals.filter(d=>!["won","lost"].includes(d.stage));return{active:active.length,pipeline:active.reduce((s,d)=>s+Number(d.value),0),weighted:active.reduce((s,d)=>s+Number(d.value)*d.probability/100,0),won:deals.filter(d=>d.stage==="won").reduce((s,d)=>s+Number(d.value),0)};},[deals]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setNotice("");try{await apiRequest("/api/partners/crm/deals",{method:"POST",body:JSON.stringify(form)});setForm(fresh);setOpen(false);await load();setNotice("Satış fırsatı CRM'e eklendi.");}catch(err){setNotice(err instanceof Error?err.message:"Fırsat eklenemedi.");}finally{setBusy(false);}};
  const move=async(id:number,stage:Stage)=>{setBusy(true);try{await apiRequest(`/api/partners/crm/deals/${id}`,{method:"PATCH",body:JSON.stringify({stage})});await load();}catch(e){setNotice(e instanceof Error?e.message:"Aşama güncellenemedi.");}finally{setBusy(false);}};
  const addActivity=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);try{await apiRequest(`/api/partners/crm/deals/${selected}/activities`,{method:"POST",body:JSON.stringify(activity)});setActivity({kind:"note",detail:""});await load();}catch(err){setNotice(err instanceof Error?err.message:"Aktivite eklenemedi.");}finally{setBusy(false);}};
  const selectedDeal=deals.find(d=>d.id===selected);
  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.22em] text-indigo-300/80">Kalıcı satış yönetimi</p><h1 className="mt-2 text-[30px] font-black tracking-[-.04em]">CRM satış pipeline</h1><p className="mt-2 text-sm text-slate-400">Fırsatları, takip tarihlerini ve satış aktivitelerini tek merkezden yönetin.</p></div><button onClick={()=>setOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 to-violet-500 px-4 py-3 text-xs font-black shadow-lg shadow-indigo-950/30"><Plus className="h-4 w-4" />Yeni fırsat</button></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Aktif fırsat" value={String(summary.active)}/><Metric icon={CircleDollarSign} label="Pipeline değeri" value={money(summary.pipeline)}/><Metric icon={Target} label="Ağırlıklı tahmin" value={money(summary.weighted)}/><Metric icon={TrendingUp} label="Kazanılan ciro" value={money(summary.won)}/></div>
    {notice?<p className="rounded-xl border border-indigo-400/15 bg-indigo-400/[.07] px-4 py-3 text-xs font-bold text-indigo-100">{notice}</p>:null}
    {open?<form onSubmit={submit} className="rounded-2xl border border-indigo-400/20 bg-[#111426]/90 p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Text label="Firma *" value={form.companyName} set={companyName=>setForm({...form,companyName})} required/><Text label="Yetkili" value={form.contactName} set={contactName=>setForm({...form,contactName})}/><Text label="Telefon" value={form.phone} set={phone=>setForm({...form,phone})}/><Text label="E-posta" value={form.email} set={email=>setForm({...form,email})} type="email"/><Text label="Hizmet *" value={form.service} set={service=>setForm({...form,service})} required/><Num label="Fırsat tutarı" value={form.value} set={value=>setForm({...form,value})}/><Text label="Sonraki aksiyon" value={form.nextAction} set={nextAction=>setForm({...form,nextAction})}/><Text label="Takip tarihi" value={form.followUpAt} set={followUpAt=>setForm({...form,followUpAt})} type="date"/></div><label className="mt-3 block text-xs font-bold text-slate-400">Not<textarea rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className={field}/></label><button disabled={busy} className="mt-4 rounded-xl bg-indigo-500 px-4 py-2.5 text-xs font-black disabled:opacity-50">{busy?"Kaydediliyor…":"CRM'e kaydet"}</button></form>:null}
    {loading?<p className="text-sm text-slate-500">CRM yükleniyor…</p>:<div className="grid gap-3 overflow-x-auto pb-2 xl:grid-cols-6">{STAGES.map(stage=><section key={stage.id} className="min-w-[250px] rounded-2xl border border-white/[.07] bg-white/[.025] p-3"><div className="mb-3 flex items-center justify-between"><span className={`rounded-lg border px-2.5 py-1 text-[10px] font-black ${stage.color}`}>{stage.label}</span><b className="text-xs text-slate-500">{deals.filter(d=>d.stage===stage.id).length}</b></div><div className="space-y-2">{deals.filter(d=>d.stage===stage.id).map(deal=>{const next=STAGES[STAGES.findIndex(s=>s.id===deal.stage)+1];return <article key={deal.id} onClick={()=>setSelected(deal.id)} className={`cursor-pointer rounded-xl border p-3.5 transition ${selected===deal.id?"border-indigo-400/40 bg-indigo-400/10":"border-white/[.07] bg-[#0c0f1b] hover:border-white/15"}`}><div className="flex justify-between gap-2"><div><h3 className="text-sm font-black">{deal.company_name}</h3><p className="mt-1 text-[10px] text-slate-500">{deal.service}</p></div><span className="text-[10px] font-black text-indigo-300">%{deal.probability}</span></div><p className="mt-3 text-lg font-black">{money(deal.value)}</p>{deal.next_action?<p className="mt-3 line-clamp-2 text-[10px] text-slate-400">{deal.next_action}</p>:null}<div className="mt-3 flex justify-between text-[9px] text-slate-600"><span className="inline-flex items-center gap-1"><CalendarClock className="h-3 w-3"/>{deal.follow_up_at||"Tarih yok"}</span><span className="inline-flex items-center gap-1"><Activity className="h-3 w-3"/>{deal.activity_count}</span></div>{next&&deal.stage!=="lost"?<button type="button" disabled={busy} onClick={e=>{e.stopPropagation();void move(deal.id,next.id);}} className="mt-3 inline-flex w-full items-center justify-center gap-1 rounded-lg border border-white/[.07] py-2 text-[9px] font-black text-slate-400 hover:text-white">{next.label}<ArrowRight className="h-3 w-3"/></button>:null}</article>;})}</div></section>)}</div>}
    {selectedDeal?<section className="rounded-2xl border border-indigo-400/20 bg-gradient-to-br from-indigo-500/[.08] to-transparent p-5"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase text-indigo-300">Fırsat detayı</p><h2 className="mt-2 text-xl font-black">{selectedDeal.company_name}</h2><p className="mt-1 text-xs text-slate-400">{selectedDeal.contact_name||"Yetkili belirtilmedi"} · {selectedDeal.phone||"Telefon yok"}</p></div><button onClick={()=>setSelected(null)} className="text-xs text-slate-500">Kapat</button></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="text-xs font-black">Aktivite geçmişi</h3><div className="mt-3 max-h-56 space-y-2 overflow-y-auto">{activities.filter(a=>a.deal_id===selectedDeal.id).map(a=><div key={a.id} className="rounded-xl bg-black/20 p-3"><p className="text-xs text-slate-300">{a.detail}</p><p className="mt-1 text-[9px] text-slate-600">{new Date(a.created_at).toLocaleString("tr-TR")}</p></div>)}</div></div><form onSubmit={addActivity}><h3 className="text-xs font-black">Yeni aktivite</h3><select value={activity.kind} onChange={e=>setActivity({...activity,kind:e.target.value})} className={field}><option value="note">Not</option><option value="call">Telefon görüşmesi</option><option value="meeting">Toplantı</option><option value="email">E-posta</option></select><textarea required rows={3} value={activity.detail} onChange={e=>setActivity({...activity,detail:e.target.value})} placeholder="Görüşme sonucu ve sonraki adım…" className={field}/><button disabled={busy} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-2.5 text-xs font-black"><MessageSquarePlus className="h-4 w-4"/>Aktivite ekle</button></form></div></section>:null}
  </div>;
}
function money(v:number){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(v)}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}){return <article className="rounded-2xl border border-white/[.07] bg-white/[.03] p-4"><div className="flex items-center gap-2 text-slate-500"><Icon className="h-4 w-4"/><span className="text-[10px] font-black uppercase">{label}</span></div><p className="mt-3 text-2xl font-black">{value}</p></article>}
function Text({label,value,set,type="text",required=false}:{label:string;value:string;set:(v:string)=>void;type?:string;required?:boolean}){return <label className="text-xs font-bold text-slate-400">{label}<input required={required} type={type} value={value} onChange={e=>set(e.target.value)} className={field}/></label>}
function Num({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="text-xs font-bold text-slate-400">{label}<input type="number" min="0" value={value} onChange={e=>set(Number(e.target.value))} className={field}/></label>}
