import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CircleCheck, Clock3, Headphones, Inbox, MessageCircle, Plus, Send, ShieldCheck } from "lucide-react";
import { apiRequest } from "../lib/api";
type Conversation={id:number;subject:string;category:string;priority:string;status:string;assigned_to:string;last_message_at:string};
type Message={id:number;conversation_id:number;sender_type:"partner"|"admin";sender_name:string;body:string;created_at:string};
const STATUS:Record<string,string>={open:"Yanıt bekliyor",pending:"Bayi yanıtı bekleniyor",resolved:"Çözüldü",closed:"Kapatıldı"};
const CATEGORY:Record<string,string>={technical:"Teknik",sales:"Satış",finance:"Finans",contract:"Sözleşme",general:"Genel"};
const field="w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/50";
export function PartnerSupportCenter(){
 const [conversations,setConversations]=useState<Conversation[]>([]),[messages,setMessages]=useState<Message[]>([]),[selected,setSelected]=useState<number|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[reply,setReply]=useState("");
 const [form,setForm]=useState({subject:"",category:"technical",priority:"normal",message:""});
 const load=useCallback(async()=>{try{const data=await apiRequest<{conversations:Conversation[];messages:Message[]}>("/api/partners/support/conversations");setConversations(data.conversations);setMessages(data.messages);setSelected(current=>current??data.conversations[0]?.id??null);}catch(e){setNotice(e instanceof Error?e.message:"Destek merkezi yüklenemedi.");}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),2500);return()=>window.clearInterval(timer);},[load]); const selectedConversation=conversations.find(c=>c.id===selected); const thread=useMemo(()=>messages.filter(m=>m.conversation_id===selected),[messages,selected]);
 useEffect(()=>{if(!selected)return;void apiRequest(`/api/partners/support/conversations/${selected}/read`,{method:"PATCH"});},[selected,thread.length]);
 const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const result=await apiRequest<{id:number}>("/api/partners/support/conversations",{method:"POST",body:JSON.stringify(form)});setForm({subject:"",category:"technical",priority:"normal",message:""});setOpen(false);await load();setSelected(result.id);}catch(err){setNotice(err instanceof Error?err.message:"Konuşma açılamadı.");}finally{setBusy(false);}};
 const send=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);try{await apiRequest(`/api/partners/support/conversations/${selected}/messages`,{method:"POST",body:JSON.stringify({message:reply})});setReply("");await load();}catch(err){setNotice(err instanceof Error?err.message:"Mesaj gönderilemedi.");}finally{setBusy(false);}};
 return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.22em] text-cyan-300/80">Bayi iletişim merkezi</p><h1 className="mt-2 text-[30px] font-black tracking-[-.04em]">Hatay360 Destek</h1><p className="mt-2 text-sm text-slate-400">Ekibimizle kayıtlı, takip edilebilir ve güvenli destek konuşmaları yürütün.</p></div><button onClick={()=>setOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-3 text-xs font-black text-slate-950"><Plus className="h-4 w-4"/>Yeni konuşma</button></header>
 <div className="grid gap-3 sm:grid-cols-3"><Info icon={Headphones} title="Tek merkez" text="Tüm görüşmeler ve yanıtlar kalıcı kayıt altında."/><Info icon={Clock3} title="Durum takibi" text="Açık, bekleyen ve çözülen talepleri görün."/><Info icon={ShieldCheck} title="Bayi gizliliği" text="Her bayi yalnızca kendi konuşmalarına erişir."/></div>
 {notice?<p className="rounded-xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-xs text-rose-100">{notice}</p>:null}
 {open?<form onSubmit={create} className="rounded-2xl border border-cyan-400/20 bg-cyan-400/[.04] p-5"><div className="grid gap-3 sm:grid-cols-3"><input required minLength={3} placeholder="Konuşma konusu" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} className={field}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className={field}><option value="technical">Teknik destek</option><option value="sales">Satış desteği</option><option value="finance">Finans / ödeme</option><option value="contract">Sözleşme</option><option value="general">Genel</option></select><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className={field}><option value="normal">Normal öncelik</option><option value="high">Yüksek öncelik</option><option value="urgent">Acil</option></select></div><textarea required minLength={5} rows={4} placeholder="Sorununuzu, aldığınız hatayı ve beklediğiniz sonucu açıklayın…" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} className={`mt-3 ${field}`}/><button disabled={busy} className="mt-3 rounded-xl bg-cyan-500 px-4 py-2.5 text-xs font-black text-slate-950 disabled:opacity-50">Konuşmayı başlat</button></form>:null}
 <div className="grid overflow-hidden rounded-2xl border border-white/[.08] bg-[#0b0e18] lg:h-[min(680px,calc(100vh-150px))] lg:min-h-[540px] lg:grid-cols-[330px_1fr]"><aside className="flex min-h-0 flex-col border-b border-white/[.07] lg:border-b-0 lg:border-r"><div className="shrink-0 border-b border-white/[.07] p-4"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Konuşmalar · {conversations.length}</p></div><div className="max-h-72 overflow-y-auto lg:max-h-none lg:min-h-0 lg:flex-1">{conversations.length?conversations.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`w-full border-b border-white/[.05] p-4 text-left transition ${selected===c.id?"bg-cyan-400/[.09]":"hover:bg-white/[.025]"}`}><div className="flex items-center justify-between gap-2"><span className="text-[9px] font-black uppercase text-cyan-300">{CATEGORY[c.category]||c.category}</span>{c.priority!=="normal"?<span className="rounded-full bg-rose-400/15 px-2 py-1 text-[8px] font-black text-rose-200">{c.priority==="urgent"?"ACİL":"YÜKSEK"}</span>:null}</div><p className="mt-2 truncate text-sm font-black">{c.subject}</p><div className="mt-2 flex justify-between text-[9px] text-slate-500"><span>{STATUS[c.status]||c.status}</span><span>{new Date(c.last_message_at).toLocaleDateString("tr-TR")}</span></div></button>):<div className="p-8 text-center"><Inbox className="mx-auto h-7 w-7 text-slate-700"/><p className="mt-3 text-xs text-slate-500">Henüz konuşma yok.</p></div>}</div></aside>
 <main className="flex min-h-[480px] min-w-0 flex-col lg:min-h-0">{selectedConversation?<><div className="shrink-0 flex items-center justify-between border-b border-white/[.07] px-5 py-4"><div><h2 className="text-sm font-black">{selectedConversation.subject}</h2><p className="mt-1 text-[10px] text-slate-500">{STATUS[selectedConversation.status]}{selectedConversation.assigned_to?` · ${selectedConversation.assigned_to}`:""}</p></div><span className={`rounded-full px-3 py-1.5 text-[9px] font-black ${selectedConversation.status==="resolved"?"bg-emerald-400/10 text-emerald-200":"bg-amber-400/10 text-amber-200"}`}>{selectedConversation.status==="resolved"?<CircleCheck className="mr-1 inline h-3 w-3"/>:<MessageCircle className="mr-1 inline h-3 w-3"/>}{STATUS[selectedConversation.status]}</span></div><div className="min-h-0 flex-1 space-y-4 overflow-y-auto overscroll-contain p-5">{thread.map(m=><div key={m.id} className={`flex ${m.sender_type==="partner"?"justify-end":"justify-start"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 ${m.sender_type==="partner"?"rounded-br-sm bg-indigo-500 text-white":"rounded-bl-sm border border-cyan-400/15 bg-cyan-400/[.07] text-slate-200"}`}><p className="text-[9px] font-black uppercase opacity-60">{m.sender_name}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-relaxed">{m.body}</p><p className="mt-2 text-right text-[8px] opacity-45">{new Date(m.created_at).toLocaleString("tr-TR")}</p></div></div>)}</div><form onSubmit={send} className="flex shrink-0 gap-2 border-t border-white/[.07] p-4"><textarea required rows={2} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Mesajınızı yazın…" className={`${field} resize-none`}/><button disabled={busy} className="grid w-12 shrink-0 place-items-center rounded-xl bg-cyan-500 text-slate-950 disabled:opacity-50"><Send className="h-4 w-4"/></button></form></>:<div className="grid flex-1 place-items-center text-center"><div><MessageCircle className="mx-auto h-10 w-10 text-slate-700"/><p className="mt-3 text-sm font-bold text-slate-500">Bir konuşma seçin veya yenisini başlatın.</p></div></div>}</main></div></div>;
}
function Info({icon:Icon,title,text}:{icon:typeof Headphones;title:string;text:string}){return <article className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><Icon className="h-5 w-5 text-cyan-300"/><p className="mt-3 text-sm font-black">{title}</p><p className="mt-1 text-[10px] leading-relaxed text-slate-500">{text}</p></article>}
