import { useMemo, useState } from "react";
import { BookOpenCheck, CalendarClock, CalendarRange, CheckCircle2, ClipboardList, Flame, Gauge, GraduationCap, PhoneForwarded, Star, Target } from "lucide-react";

type Tool = "score" | "followup" | "meeting" | "academy" | "campaign";
const TOOLS = [
  { id: "score" as const, label: "Fırsat puanı", icon: Gauge },
  { id: "followup" as const, label: "Takip planı", icon: PhoneForwarded },
  { id: "meeting" as const, label: "Görüşme hazırlığı", icon: ClipboardList },
  { id: "academy" as const, label: "Bayi akademisi", icon: GraduationCap },
  { id: "campaign" as const, label: "Kampanya planı", icon: CalendarRange },
];
const MEETING_STEPS = ["İşletmenin web ve Maps durumunu kontrol et", "Karar vericinin adını öğren", "Üç ihtiyaç sorusu hazırla", "Uygun demo ve referansı seç", "Net sonraki adımı belirle"];
const LESSONS = [
  { title: "Dijital ihtiyaç keşfi", minutes: 8, desc: "Müşterinin gerçek sorununu fiyat konuşmadan önce belirleme." },
  { title: "Google Ads temelleri", minutes: 12, desc: "Reklam bütçesi ile yönetim ücretini doğru anlatma." },
  { title: "Kurumsal web satışı", minutes: 10, desc: "Tasarım yerine güven, çağrı ve dönüşüm faydasını satma." },
  { title: "İtiraz ve kapanış", minutes: 9, desc: "Kararı zorlamadan net sonraki adım alma." },
];
const CAMPAIGNS = ["Yeni müşteri kazanımı", "Web sitesi yenileme", "Google Maps görünürlüğü", "Sezon kampanyası", "Bakım / SEO yenileme"];

export function PartnerOperationsToolsSection() {
  const [tool, setTool] = useState<Tool>("score");
  const [score, setScore] = useState({ need: 3, budget: 3, authority: 3, timing: 3 });
  const [followups, setFollowups] = useState<{ company: string; date: string; note: string }[]>([]);
  const [followup, setFollowup] = useState({ company: "", date: "", note: "" });
  const [meeting, setMeeting] = useState<boolean[]>(MEETING_STEPS.map(() => false));
  const [lessons, setLessons] = useState<boolean[]>(LESSONS.map(() => false));
  const [campaign, setCampaign] = useState({ type: CAMPAIGNS[0], audience: "", offer: "", start: "", end: "" });
  const totalScore = score.need + score.budget + score.authority + score.timing;
  const scoreLabel = totalScore >= 16 ? "Sıcak fırsat" : totalScore >= 11 ? "Takip edilmeli" : "Erken aşama";
  const campaignPlan = useMemo(() => `${campaign.type}: ${campaign.audience || "hedef kitle"} için ${campaign.offer || "net teklif"}. ${campaign.start || "başlangıç"} – ${campaign.end || "bitiş"} arasında telefon, WhatsApp ve teklif dönüşümleri takip edilir.`, [campaign]);

  return <div className="space-y-6">
    <header><p className="text-[11px] font-black uppercase tracking-[0.22em] text-indigo-300/80">Bayi çalışma sistemi</p><h1 className="mt-2 text-[30px] font-black tracking-[-0.04em]">Operasyon merkezi</h1><p className="mt-2 text-sm text-indigo-100/55">Fırsatları puanlayın, görüşmeleri planlayın ve satış becerinizi geliştirin.</p></header>
    <div className="flex gap-2 overflow-x-auto pb-1">{TOOLS.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTool(item.id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3.5 py-2.5 text-xs font-black ${tool === item.id ? "bg-violet-500 text-white" : "border border-indigo-400/15 bg-indigo-500/5 text-indigo-100/60"}`}><Icon className="h-4 w-4" />{item.label}</button>; })}</div>

    {tool === "score" ? <section className="rounded-2xl border border-indigo-400/20 bg-[#15122f]/80 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Müşteri fırsat puanlayıcı</h2><p className="mt-1 text-xs text-indigo-100/45">Dört satış sinyalini 1–5 arasında puanlayın.</p></div><div className={`rounded-xl px-4 py-2 text-center ${totalScore >= 16 ? "bg-emerald-400/15 text-emerald-100" : totalScore >= 11 ? "bg-amber-400/15 text-amber-100" : "bg-indigo-400/15 text-indigo-100"}`}><p className="text-2xl font-black">{totalScore}/20</p><p className="text-[10px] font-black uppercase">{scoreLabel}</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{([['need','İhtiyaç seviyesi'],['budget','Bütçe uygunluğu'],['authority','Karar yetkisi'],['timing','Satın alma zamanı']] as const).map(([key,label]) => <label key={key} className="rounded-xl bg-black/20 p-4 text-xs font-bold text-indigo-100/65">{label}<input type="range" min="1" max="5" value={score[key]} onChange={(e) => setScore({ ...score, [key]: Number(e.target.value) })} className="mt-3 w-full accent-violet-500" /><span className="mt-1 block text-right text-sm font-black text-violet-200">{score[key]}/5</span></label>)}</div></section> : null}

    {tool === "followup" ? <section className="space-y-4"><div className="rounded-2xl border border-sky-400/20 bg-sky-400/5 p-5"><h2 className="font-black">Takip hatırlatıcısı</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><input value={followup.company} onChange={(e) => setFollowup({ ...followup, company: e.target.value })} placeholder="Firma adı" className="rounded-xl border border-indigo-400/20 bg-black/25 px-3 py-2.5 text-sm" /><input type="date" value={followup.date} onChange={(e) => setFollowup({ ...followup, date: e.target.value })} className="rounded-xl border border-indigo-400/20 bg-black/25 px-3 py-2.5 text-sm" /><input value={followup.note} onChange={(e) => setFollowup({ ...followup, note: e.target.value })} placeholder="Takip notu" className="rounded-xl border border-indigo-400/20 bg-black/25 px-3 py-2.5 text-sm" /></div><button onClick={() => { if (!followup.company || !followup.date) return; setFollowups((old) => [...old, followup].sort((a,b) => a.date.localeCompare(b.date))); setFollowup({ company: "", date: "", note: "" }); }} className="mt-3 rounded-lg bg-sky-500 px-4 py-2 text-xs font-black">Takibe ekle</button></div>{followups.map((item, index) => <article key={`${item.company}-${item.date}-${index}`} className="flex items-center gap-3 rounded-xl border border-indigo-400/15 bg-[#15122f]/60 p-4"><CalendarClock className="h-5 w-5 text-sky-300" /><div className="flex-1"><p className="text-sm font-black">{item.company}</p><p className="text-xs text-indigo-100/45">{item.date} · {item.note || "Takip görüşmesi"}</p></div><button onClick={() => setFollowups((old) => old.filter((_, i) => i !== index))} className="text-xs font-black text-emerald-300">Tamamla</button></article>)}</section> : null}

    {tool === "meeting" ? <section className="rounded-2xl border border-amber-400/20 bg-amber-400/5 p-6"><div className="flex items-center justify-between"><h2 className="font-black">Satış görüşmesi hazırlığı</h2><span className="text-xs font-black text-amber-200">{meeting.filter(Boolean).length}/{MEETING_STEPS.length}</span></div><div className="mt-4 space-y-2">{MEETING_STEPS.map((item,index) => <label key={item} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm ${meeting[index] ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-100" : "border-indigo-400/15 bg-black/15 text-indigo-100/70"}`}><input type="checkbox" checked={meeting[index]} onChange={(e) => setMeeting((old) => old.map((x,i) => i === index ? e.target.checked : x))} /><CheckCircle2 className="h-4 w-4" />{item}</label>)}</div>{meeting.every(Boolean) ? <p className="mt-4 flex items-center gap-2 text-sm font-black text-emerald-200"><Star className="h-4 w-4" />Görüşmeye hazırsınız.</p> : null}</section> : null}

    {tool === "academy" ? <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-black">Bayi satış akademisi</h2><span className="rounded-full bg-violet-500/15 px-3 py-1 text-xs font-black text-violet-200">%{Math.round(lessons.filter(Boolean).length / LESSONS.length * 100)}</span></div>{LESSONS.map((lesson,index) => <article key={lesson.title} className="flex items-start gap-4 rounded-2xl border border-indigo-400/15 bg-[#15122f]/70 p-5"><span className={`rounded-xl p-2.5 ${lessons[index] ? "bg-emerald-400/15 text-emerald-200" : "bg-indigo-500/15 text-indigo-200"}`}><BookOpenCheck className="h-5 w-5" /></span><div className="flex-1"><p className="font-black">{lesson.title}</p><p className="mt-1 text-xs leading-relaxed text-indigo-100/50">{lesson.desc}</p><p className="mt-2 text-[10px] font-black uppercase text-indigo-300/60">{lesson.minutes} dakika</p></div><button onClick={() => setLessons((old) => old.map((x,i) => i === index ? !x : x))} className="text-xs font-black text-violet-200">{lessons[index] ? "Tamamlandı" : "Tamamla"}</button></article>)}</section> : null}

    {tool === "campaign" ? <section className="rounded-2xl border border-fuchsia-400/20 bg-fuchsia-400/5 p-6"><h2 className="font-black">Mini kampanya planlayıcı</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={campaign.type} onChange={(e) => setCampaign({ ...campaign, type: e.target.value })} className="rounded-xl border border-indigo-400/20 bg-[#12102a] px-3 py-2.5 text-sm">{CAMPAIGNS.map((x) => <option key={x}>{x}</option>)}</select><input value={campaign.audience} onChange={(e) => setCampaign({ ...campaign, audience: e.target.value })} placeholder="Hedef kitle" className="rounded-xl border border-indigo-400/20 bg-black/25 px-3 py-2.5 text-sm" /><input value={campaign.offer} onChange={(e) => setCampaign({ ...campaign, offer: e.target.value })} placeholder="Teklif / mesaj" className="rounded-xl border border-indigo-400/20 bg-black/25 px-3 py-2.5 text-sm" /><div className="grid grid-cols-2 gap-2"><input type="date" value={campaign.start} onChange={(e) => setCampaign({ ...campaign, start: e.target.value })} className="rounded-xl border border-indigo-400/20 bg-black/25 px-3 py-2.5 text-xs" /><input type="date" value={campaign.end} onChange={(e) => setCampaign({ ...campaign, end: e.target.value })} className="rounded-xl border border-indigo-400/20 bg-black/25 px-3 py-2.5 text-xs" /></div></div><div className="mt-5 rounded-xl bg-black/20 p-4"><p className="flex items-center gap-2 text-xs font-black uppercase text-fuchsia-200"><Flame className="h-4 w-4" />Kampanya özeti</p><p className="mt-2 text-sm leading-relaxed text-indigo-100/70">{campaignPlan}</p></div></section> : null}
  </div>;
}
