import { useMemo, useState, type ReactNode } from "react";
import { CircleDollarSign, ClipboardList, Copy, FileQuestion, Gauge, Headphones, KeyRound, MailCheck, Megaphone, ReceiptText, TimerReset } from "lucide-react";

type Tool = "lead" | "margin" | "call" | "subject" | "cta" | "keyword" | "campaign" | "payment" | "survey" | "sla";
const TOOLS = [
  { id: "lead" as const, label: "Müşteri puanı", icon: Gauge },
  { id: "margin" as const, label: "Kârlılık", icon: CircleDollarSign },
  { id: "call" as const, label: "Arama senaryosu", icon: Headphones },
  { id: "subject" as const, label: "E-posta başlığı", icon: MailCheck },
  { id: "cta" as const, label: "CTA üretici", icon: Megaphone },
  { id: "keyword" as const, label: "Yerel kelimeler", icon: KeyRound },
  { id: "campaign" as const, label: "Kampanya adı", icon: ClipboardList },
  { id: "payment" as const, label: "Ödeme mesajı", icon: ReceiptText },
  { id: "survey" as const, label: "Memnuniyet", icon: FileQuestion },
  { id: "sla" as const, label: "Hizmet süresi", icon: TimerReset },
];
const inputClass = "mt-1.5 w-full rounded-xl border border-teal-400/20 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-teal-300/50";

export function PartnerSmartToolsSection() {
  const [tool, setTool] = useState<Tool>("lead");
  const [copied, setCopied] = useState("");
  const [lead, setLead] = useState({ budget: 3, urgency: 3, authority: 2, need: 3 });
  const [margin, setMargin] = useState({ price: 25000, labor: 8000, ads: 2500, other: 1500 });
  const [call, setCall] = useState({ name: "", sector: "", goal: "daha fazla müşteri kazanmak" });
  const [subject, setSubject] = useState({ company: "", benefit: "dijital görünürlüğü artırma", tone: "professional" });
  const [cta, setCta] = useState({ service: "Kurumsal web sitesi", action: "Ücretsiz analiz alın", urgency: "Bugün" });
  const [keyword, setKeyword] = useState({ city: "Hatay", district: "Antakya", sector: "web tasarım" });
  const [campaign, setCampaign] = useState({ brand: "Hatay360", channel: "Google", goal: "Lead", month: "Eylül" });
  const [payment, setPayment] = useState({ customer: "", amount: 7500, date: "", tone: "gentle" });
  const [survey, setSurvey] = useState({ customer: "", service: "Web sitesi" });
  const [sla, setSla] = useState({ priority: "normal", workHours: 6, dailyCapacity: 4 });

  const leadScore = Object.values(lead).reduce((sum, value) => sum + value, 0);
  const leadStatus = leadScore >= 10 ? "Sıcak müşteri" : leadScore >= 7 ? "Takip edilmeli" : "Uzun vadeli aday";
  const costs = margin.labor + margin.ads + margin.other;
  const profit = margin.price - costs;
  const marginRate = margin.price ? profit / margin.price * 100 : 0;
  const callText = `Merhaba ${call.name || "[Müşteri adı]"}, ben Hatay360 yetkili bayisinden arıyorum. ${call.sector || "işletmeniz"} için ${call.goal} hedefinize yönelik kısa bir dijital ön analiz hazırladık. Mevcut durumunuzu anlamak için size üç kısa soru sorabilir miyim?\n\n1. Şu anda müşterileriniz sizi en çok nereden buluyor?\n2. Aylık yeni müşteri hedefiniz nedir?\n3. Dijital tarafta öncelikle çözmek istediğiniz konu hangisi?`;
  const subjects = subject.tone === "direct" ? [`${subject.company || "Firmanız"} için hızlı büyüme fırsatı`, `${subject.benefit}: 3 net adım`, `Teklifinizi birlikte netleştirelim`] : [`${subject.company || "Firmanız"} için ${subject.benefit} önerisi`, `Dijital büyüme planınızı hazırladık`, `${subject.company || "Markanız"} için ön analiz ve sonraki adımlar`];
  const ctaText = `${cta.urgency} ${cta.action} — ${cta.service} ile markanızı güvenle büyütün.`;
  const keywords = useMemo(() => [`${keyword.city} ${keyword.sector}`, `${keyword.district} ${keyword.sector}`, `${keyword.sector} fiyatları ${keyword.city}`, `en iyi ${keyword.sector} ${keyword.district}`, `${keyword.city} kurumsal ${keyword.sector}`, `${keyword.sector} firması ${keyword.city}`], [keyword]);
  const campaignName = `${campaign.brand}_${campaign.channel}_${campaign.goal}_${campaign.month}`.replace(/\s+/g, "-").toLocaleLowerCase("tr-TR");
  const paymentText = payment.tone === "firm" ? `Merhaba ${payment.customer || "[Müşteri adı]"}, ₺${payment.amount.toLocaleString("tr-TR")} tutarındaki ödemenizin son tarihi ${payment.date || "[tarih]"}. Hizmetin kesintisiz devamı için ödemenizi tarihine kadar tamamlamanızı rica ederiz.` : `Merhaba ${payment.customer || "[Müşteri adı]"}, ₺${payment.amount.toLocaleString("tr-TR")} tutarındaki ödemeniz için ${payment.date || "[tarih]"} tarihini hatırlatmak istedik. Ödeme veya süreçle ilgili desteğe ihtiyacınız olursa bize yazabilirsiniz.`;
  const surveyText = `Merhaba ${survey.customer || "[Müşteri adı]"}, ${survey.service} hizmetimizle ilgili deneyiminizi geliştirmek istiyoruz. 1-10 arasında memnuniyet puanınız nedir? En beğendiğiniz konu ve geliştirmemizi istediğiniz tek nokta nedir? Yanıtınız hizmet kalitemiz için çok değerli.`;
  const responseHours = sla.priority === "urgent" ? 1 : sla.priority === "high" ? 4 : 8;
  const deliveryDays = Math.max(1, Math.ceil(sla.workHours / Math.max(1, sla.dailyCapacity)));
  const copy = async (id: string, text: string) => { await navigator.clipboard.writeText(text); setCopied(id); window.setTimeout(() => setCopied(""), 1500); };

  return <div className="space-y-6">
    <header><p className="text-[11px] font-black uppercase tracking-[0.22em] text-teal-300/80">Günlük bayi asistanı</p><h1 className="mt-2 text-[30px] font-black tracking-[-0.04em]">Akıllı iş araçları</h1><p className="mt-2 text-sm text-indigo-100/55">Müşteri değerlendirme, kârlılık ve iletişim işlerini hızlandıran 10 araç.</p></header>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-5">{TOOLS.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTool(item.id)} className={`inline-flex items-center gap-2 rounded-xl px-3 py-3 text-left text-xs font-black ${tool === item.id ? "bg-teal-500 text-white shadow-lg shadow-teal-950/30" : "border border-teal-400/15 bg-teal-500/5 text-teal-100/60"}`}><Icon className="h-4 w-4 shrink-0" />{item.label}</button>; })}</div>

    {tool === "lead" ? <Card title="1. Potansiyel müşteri puanlama"><div className="grid gap-4 sm:grid-cols-2">{([['budget','Bütçe uygunluğu'],['urgency','Başlama aciliyeti'],['authority','Karar yetkisi'],['need','Hizmet ihtiyacı']] as const).map(([key,label]) => <label key={key} className="text-xs font-bold text-teal-100/60">{label} · {lead[key]}/3<input type="range" min="1" max="3" value={lead[key]} onChange={(e) => setLead({ ...lead, [key]: Number(e.target.value) })} className="mt-3 w-full accent-teal-500" /></label>)}</div><Result title={leadStatus} detail={`${leadScore}/12 puan · ${leadScore >= 10 ? "24 saat içinde teklif görüşmesi planlayın." : leadScore >= 7 ? "Eksik bilgileri tamamlayıp düzenli takip edin." : "Eğitici içeriklerle ilgiyi güçlendirin."}`} /></Card> : null}
    {tool === "margin" ? <Card title="2. Proje kârlılık hesaplayıcı"><Grid><Num label="Satış fiyatı" value={margin.price} onChange={(price) => setMargin({ ...margin, price })} /><Num label="İşçilik" value={margin.labor} onChange={(labor) => setMargin({ ...margin, labor })} /><Num label="Reklam / araç" value={margin.ads} onChange={(ads) => setMargin({ ...margin, ads })} /><Num label="Diğer maliyet" value={margin.other} onChange={(other) => setMargin({ ...margin, other })} /></Grid><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Toplam maliyet" value={`₺${costs.toLocaleString("tr-TR")}`} /><Metric label="Net kâr" value={`₺${profit.toLocaleString("tr-TR")}`} /><Metric label="Kâr marjı" value={`%${marginRate.toFixed(1)}`} /></div></Card> : null}
    {tool === "call" ? <Card title="3. İlk müşteri arama senaryosu"><Grid><Text label="Müşteri" value={call.name} onChange={(name) => setCall({ ...call, name })} /><Text label="Sektör" value={call.sector} onChange={(sector) => setCall({ ...call, sector })} /><Text label="Ana hedef" value={call.goal} onChange={(goal) => setCall({ ...call, goal })} /></Grid><CopyBox id="call" text={callText} copied={copied} copy={copy} /></Card> : null}
    {tool === "subject" ? <Card title="4. Teklif e-postası başlıkları"><Grid><Text label="Firma" value={subject.company} onChange={(company) => setSubject({ ...subject, company })} /><Text label="Ana fayda" value={subject.benefit} onChange={(benefit) => setSubject({ ...subject, benefit })} /><Select label="Ton" value={subject.tone} onChange={(tone) => setSubject({ ...subject, tone })} options={[['professional','Kurumsal'],['direct','Doğrudan']]} /></Grid><ListCopy id="subjects" items={subjects} copied={copied} copy={copy} /></Card> : null}
    {tool === "cta" ? <Card title="5. Dönüşüm çağrısı oluşturucu"><Grid><Text label="Hizmet" value={cta.service} onChange={(service) => setCta({ ...cta, service })} /><Text label="Eylem" value={cta.action} onChange={(action) => setCta({ ...cta, action })} /><Text label="Zaman ifadesi" value={cta.urgency} onChange={(urgency) => setCta({ ...cta, urgency })} /></Grid><CopyBox id="cta" text={ctaText} copied={copied} copy={copy} /></Card> : null}
    {tool === "keyword" ? <Card title="6. Yerel anahtar kelime üretici"><Grid><Text label="Şehir" value={keyword.city} onChange={(city) => setKeyword({ ...keyword, city })} /><Text label="İlçe" value={keyword.district} onChange={(district) => setKeyword({ ...keyword, district })} /><Text label="Hizmet / sektör" value={keyword.sector} onChange={(sector) => setKeyword({ ...keyword, sector })} /></Grid><ListCopy id="keywords" items={keywords} copied={copied} copy={copy} /></Card> : null}
    {tool === "campaign" ? <Card title="7. Standart kampanya adlandırıcı"><Grid><Text label="Marka" value={campaign.brand} onChange={(brand) => setCampaign({ ...campaign, brand })} /><Text label="Kanal" value={campaign.channel} onChange={(channel) => setCampaign({ ...campaign, channel })} /><Text label="Hedef" value={campaign.goal} onChange={(goal) => setCampaign({ ...campaign, goal })} /><Text label="Dönem" value={campaign.month} onChange={(month) => setCampaign({ ...campaign, month })} /></Grid><CopyBox id="campaign" text={campaignName} copied={copied} copy={copy} /></Card> : null}
    {tool === "payment" ? <Card title="8. Profesyonel ödeme hatırlatması"><Grid><Text label="Müşteri" value={payment.customer} onChange={(customer) => setPayment({ ...payment, customer })} /><Num label="Tutar" value={payment.amount} onChange={(amount) => setPayment({ ...payment, amount })} /><Text label="Son tarih" value={payment.date} onChange={(date) => setPayment({ ...payment, date })} /><Select label="Ton" value={payment.tone} onChange={(tone) => setPayment({ ...payment, tone })} options={[['gentle','Nazik'],['firm','Net']]} /></Grid><CopyBox id="payment" text={paymentText} copied={copied} copy={copy} /></Card> : null}
    {tool === "survey" ? <Card title="9. Müşteri memnuniyet mesajı"><Grid><Text label="Müşteri" value={survey.customer} onChange={(customer) => setSurvey({ ...survey, customer })} /><Text label="Hizmet" value={survey.service} onChange={(service) => setSurvey({ ...survey, service })} /></Grid><CopyBox id="survey" text={surveyText} copied={copied} copy={copy} /></Card> : null}
    {tool === "sla" ? <Card title="10. Hizmet yanıt ve teslim planı"><Grid><Select label="Öncelik" value={sla.priority} onChange={(priority) => setSla({ ...sla, priority })} options={[['normal','Normal'],['high','Yüksek'],['urgent','Acil']]} /><Num label="Tahmini iş saati" value={sla.workHours} onChange={(workHours) => setSla({ ...sla, workHours })} /><Num label="Günlük kapasite" value={sla.dailyCapacity} onChange={(dailyCapacity) => setSla({ ...sla, dailyCapacity })} /></Grid><div className="mt-5 grid gap-3 sm:grid-cols-2"><Metric label="İlk yanıt hedefi" value={`${responseHours} saat`} /><Metric label="Tahmini teslim" value={`${deliveryDays} iş günü`} /></div><p className="mt-3 text-[11px] text-amber-100/60">Bu süreler ekip planlaması içindir; müşteriye sözleşmedeki resmi süreyi bildirin.</p></Card> : null}
  </div>;
}

function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-2xl border border-teal-400/20 bg-teal-400/5 p-5 sm:p-6"><h2 className="mb-5 text-lg font-black">{title}</h2>{children}</section>; }
function Grid({ children }: { children: ReactNode }) { return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{children}</div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-bold text-teal-100/60">{label}{children}</label>; }
function Text({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <Field label={label}><input value={value} onChange={(e) => onChange(e.target.value)} className={inputClass} /></Field>; }
function Num({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <Field label={label}><input type="number" min="0" value={value} onChange={(e) => onChange(Number(e.target.value))} className={inputClass} /></Field>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string,string][] }) { return <Field label={label}><select value={value} onChange={(e) => onChange(e.target.value)} className={inputClass}>{options.map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select></Field>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-black/20 p-4"><p className="text-[10px] font-black uppercase text-teal-200/50">{label}</p><p className="mt-2 text-2xl font-black text-teal-100">{value}</p></div>; }
function Result({ title, detail }: { title: string; detail: string }) { return <div className="mt-5 rounded-xl bg-teal-400/10 p-5"><p className="text-xl font-black text-teal-100">{title}</p><p className="mt-2 text-xs text-teal-50/65">{detail}</p></div>; }
function CopyBox({ id, text, copied, copy }: { id: string; text: string; copied: string; copy: (id: string, text: string) => Promise<void> }) { return <div className="mt-5 rounded-xl bg-black/20 p-4"><p className="whitespace-pre-line text-sm leading-relaxed text-indigo-50/75">{text}</p><button onClick={() => void copy(id,text)} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-teal-400/25 px-3 py-2 text-xs font-black text-teal-100"><Copy className="h-3.5 w-3.5" />{copied === id ? "Kopyalandı" : "Metni kopyala"}</button></div>; }
function ListCopy({ id, items, copied, copy }: { id: string; items: string[]; copied: string; copy: (id: string, text: string) => Promise<void> }) { return <div className="mt-5"><div className="grid gap-2 sm:grid-cols-2">{items.map((item) => <p key={item} className="rounded-xl bg-black/20 p-3 text-sm text-indigo-50/75">{item}</p>)}</div><button onClick={() => void copy(id,items.join("\n"))} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-teal-400/25 px-3 py-2 text-xs font-black text-teal-100"><Copy className="h-3.5 w-3.5" />{copied === id ? "Kopyalandı" : "Listeyi kopyala"}</button></div>; }
