import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Clock3, Inbox, Plus, RefreshCw, Send, UserCheck } from "lucide-react";
import { apiRequest } from "../lib/api";
type Conversation={id:number;company_name:string;contact_name:string;email:string;subject:string;department:string;priority:string;status:string;assigned_to:string;sla_due_at:string;first_response_at:string;last_message_at:string};
type Message={id:number;conversation_id:number;sender_type:string;sender_name:string;body:string;created_at:string};
type Partner={id:number;company_name:string;contact_name:string;email:string};
const DEPT:Record<string,string>={technical:"Teknik",sales:"Satış",finance:"Finans",contract:"Sözleşme",general:"Genel"};
const STATUS:Record<string,string>={open:"Açık",pending:"Bayi bekleniyor",resolved:"Çözüldü",closed:"Kapalı"};
const selectClass="rounded-xl border border-white/10 bg-[#18181f] px-3 py-2 text-[10px] text-white";
export function AdminPartnerSupportPanel(){
 const [rows,setRows]=useState<Conversation[]>([]),[messages,setMessages]=useState<Message[]>([]),[agents,setAgents]=useState<string[]>([]),[partners,setPartners]=useState<Partner[]>([]),[selected,setSelected]=useState<number|null>(null),[reply,setReply]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[creating,setCreating]=useState(false);
 const [newChat,setNewChat]=useState({partnerId:"",subject:"",department:"technical",priority:"normal",message:""});
 const [filter,setFilter]=useState({status:"active",department:"all",assignee:"all",search:""});
 const load=useCallback(async()=>{try{const data=await apiRequest<{conversations:Conversation[];messages:Message[];agents:string[];partners:Partner[]}>('/api/admin/partner-support');setRows(data.conversations);setMessages(data.messages);setAgents(data.agents||[]);setPartners(data.partners||[]);setSelected(v=>v??data.conversations[0]?.id??null);setNotice("");}catch(e){setNotice(e instanceof Error?e.message:"Destek kutusu yüklenemedi.");}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),2500);return()=>window.clearInterval(timer);},[load]);
 const active=rows.find(r=>r.id===selected),thread=useMemo(()=>messages.filter(m=>m.conversation_id===selected),[messages,selected]);
 useEffect(()=>{if(selected)void apiRequest(`/api/admin/partner-support/${selected}/read`,{method:"PATCH"});},[selected,thread.length]);
 const visible=useMemo(()=>rows.filter(r=>(filter.status==="all"||(filter.status==="active"?["open","pending"].includes(r.status):r.status===filter.status))&&(filter.department==="all"||r.department===filter.department)&&(filter.assignee==="all"||(filter.assignee==="none"?!r.assigned_to:r.assigned_to===filter.assignee))&&`${r.company_name} ${r.subject}`.toLocaleLowerCase("tr-TR").includes(filter.search.toLocaleLowerCase("tr-TR"))),[rows,filter]);
 const update=async(body:Record<string,string>)=>{if(!selected)return;setBusy(true);try{await apiRequest(`/api/admin/partner-support/${selected}/messages`,{method:"PATCH",body:JSON.stringify(body)});await load();}catch(e){setNotice(e instanceof Error?e.message:"Güncellenemedi.");}finally{setBusy(false);}};
 const send=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);try{await apiRequest(`/api/admin/partner-support/${selected}/messages`,{method:"POST",body:JSON.stringify({message:reply})});setReply("");await load();}catch(err){setNotice(err instanceof Error?err.message:"Yanıt gönderilemedi.");}finally{setBusy(false);}};
 const createChat=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const result=await apiRequest<{id:number}>("/api/admin/partner-support",{method:"POST",body:JSON.stringify({...newChat,partnerId:Number(newChat.partnerId)})});setNewChat({partnerId:"",subject:"",department:"technical",priority:"normal",message:""});setCreating(false);await load();setSelected(result.id);}catch(err){setNotice(err instanceof Error?err.message:"Konuşma açılamadı.");}finally{setBusy(false);}};
 return <div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-300">Bayi iletişim operasyonu</p><h2 className="mt-2 text-[26px] font-black">Bayi Destek Merkezi</h2><p className="mt-2 text-xs text-white/50">SLA, departman ve temsilci atamasıyla destek operasyonunu yönetin.</p></div><div className="flex gap-2"><button onClick={()=>setCreating(v=>!v)} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-3 text-[10px] font-black text-[#071318]"><Plus className="h-4 w-4"/>Bayiyle konuşma başlat</button><button onClick={()=>void load()} className="rounded-xl border border-white/10 p-3 text-white/60"><RefreshCw className="h-4 w-4"/></button></div></header>
 {creating?<form onSubmit={createChat} className="rounded-2xl border border-cyan-400/20 bg-cyan-400/[.04] p-4"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-4"><select required value={newChat.partnerId} onChange={e=>setNewChat({...newChat,partnerId:e.target.value})} className={selectClass}><option value="">Bayi seçin</option>{partners.map(p=><option key={p.id} value={p.id}>{p.company_name} · {p.contact_name}</option>)}</select><input required minLength={3} placeholder="Konuşma konusu" value={newChat.subject} onChange={e=>setNewChat({...newChat,subject:e.target.value})} className={selectClass}/><select value={newChat.department} onChange={e=>setNewChat({...newChat,department:e.target.value})} className={selectClass}>{Object.entries(DEPT).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select value={newChat.priority} onChange={e=>setNewChat({...newChat,priority:e.target.value})} className={selectClass}><option value="normal">Normal</option><option value="high">Yüksek</option><option value="urgent">Acil</option></select></div><textarea required minLength={5} rows={3} placeholder="İlk mesajınızı yazın…" value={newChat.message} onChange={e=>setNewChat({...newChat,message:e.target.value})} className={`${selectClass} mt-2 w-full resize-none`}/><button disabled={busy} className="mt-2 rounded-xl bg-cyan-500 px-4 py-2.5 text-[10px] font-black text-[#071318] disabled:opacity-50">Konuşmayı aç ve gönder</button></form>:null}
 <div className="grid gap-3 sm:grid-cols-3"><Summary label="Aktif konuşma" value={rows.filter(r=>["open","pending"].includes(r.status)).length} tone="cyan"/><Summary label="SLA geciken" value={rows.filter(overdue).length} tone="rose"/><Summary label="Atanmamış" value={rows.filter(r=>!r.assigned_to&&["open","pending"].includes(r.status)).length} tone="amber"/></div>
 <div className="grid gap-2 rounded-2xl border border-white/10 bg-white/[.025] p-3 sm:grid-cols-2 xl:grid-cols-4"><input placeholder="Firma veya konu ara…" value={filter.search} onChange={e=>setFilter({...filter,search:e.target.value})} className={selectClass}/><select value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})} className={selectClass}><option value="active">Aktif</option><option value="all">Tüm durumlar</option>{Object.entries(STATUS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select value={filter.department} onChange={e=>setFilter({...filter,department:e.target.value})} className={selectClass}><option value="all">Tüm departmanlar</option>{Object.entries(DEPT).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select value={filter.assignee} onChange={e=>setFilter({...filter,assignee:e.target.value})} className={selectClass}><option value="all">Tüm temsilciler</option><option value="none">Atanmamış</option>{agents.map(a=><option key={a}>{a}</option>)}</select></div>{notice?<p className="rounded-xl bg-rose-500/10 p-3 text-xs text-rose-100">{notice}</p>:null}
 <div className="grid overflow-hidden rounded-2xl border border-white/10 bg-[#111119] lg:h-[min(700px,calc(100vh-150px))] lg:min-h-[540px] lg:grid-cols-[350px_1fr]"><aside className="flex min-h-0 flex-col border-r border-white/10"><div className="shrink-0 p-4 text-[10px] font-black uppercase text-white/35">Gelen kutusu · {visible.length}</div><div className="min-h-0 flex-1 overflow-y-auto">{visible.length?visible.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`w-full border-t border-white/[.06] p-4 text-left ${selected===r.id?"bg-cyan-500/10":"hover:bg-white/[.03]"}`}><div className="flex justify-between"><span className="text-[9px] font-black uppercase text-cyan-300">{DEPT[r.department]||r.department} · {r.company_name}</span>{overdue(r)?<span className="inline-flex items-center gap-1 text-[8px] font-black text-rose-300"><AlertTriangle className="h-3 w-3"/>SLA</span>:null}</div><p className="mt-2 truncate text-sm font-black">{r.subject}</p><p className="mt-2 text-[9px] text-white/35">{STATUS[r.status]} · {r.assigned_to||"Atanmamış"} · {r.priority}</p></button>):<div className="p-10 text-center text-white/30"><Inbox className="mx-auto h-7 w-7"/><p className="mt-3 text-xs">Sonuç bulunamadı</p></div>}</div></aside>
 <main className="flex min-h-0 min-w-0 flex-col">{active?<><div className="shrink-0 border-b border-white/10 p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">{active.company_name}</h3><p className="mt-1 text-[10px] text-white/40">{active.contact_name} · {active.subject}</p></div><span className={`rounded-lg px-3 py-2 text-[9px] font-black ${overdue(active)?"bg-rose-500/15 text-rose-200":"bg-emerald-500/10 text-emerald-200"}`}><Clock3 className="mr-1 inline h-3 w-3"/>{active.first_response_at?"İlk yanıt verildi":overdue(active)?"SLA gecikti":`SLA ${deadline(active.sla_due_at)}`}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><select value={active.department} onChange={e=>void update({department:e.target.value})} className={selectClass}>{Object.entries(DEPT).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select value={active.assigned_to} onChange={e=>void update({assignedTo:e.target.value})} className={selectClass}><option value="">Atanmamış</option>{agents.map(a=><option key={a}>{a}</option>)}</select><select value={active.priority} onChange={e=>void update({priority:e.target.value})} className={selectClass}><option value="normal">Normal · 8 saat</option><option value="high">Yüksek · 4 saat</option><option value="urgent">Acil · 1 saat</option></select></div><div className="mt-3 flex gap-2"><button disabled={busy} onClick={()=>void update({assignedTo:agents[0]||"Hatay360 Destek"})} className="inline-flex items-center gap-1 rounded-lg border border-cyan-300/20 px-3 py-2 text-[9px] font-black"><UserCheck className="h-3 w-3"/>Bana ata</button><button onClick={()=>void update({status:"open"})} className="rounded-lg border border-amber-300/20 px-3 py-2 text-[9px] font-black">Açık</button><button onClick={()=>void update({status:"resolved"})} className="rounded-lg bg-emerald-500 px-3 py-2 text-[9px] font-black">Çözüldü</button></div></div>
 <div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-5">{thread.map(m=><div key={m.id} className={`flex ${m.sender_type==="admin"?"justify-end":"justify-start"}`}><div className={`max-w-[80%] rounded-2xl p-4 ${m.sender_type==="admin"?"bg-cyan-500 text-[#071318]":"bg-white/[.06]"}`}><p className="text-[9px] font-black uppercase opacity-55">{m.sender_name}</p><p className="mt-1 whitespace-pre-wrap break-words text-xs">{m.body}</p><p className="mt-2 text-[8px] opacity-40">{new Date(m.created_at).toLocaleString("tr-TR")}</p></div></div>)}</div><form onSubmit={send} className="flex shrink-0 gap-2 border-t border-white/10 p-4"><textarea required rows={2} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Bayi yanıtınızı yazın…" className="w-full resize-none rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-xs"/><button disabled={busy} className="w-14 rounded-xl bg-cyan-500 text-[#071318]"><Send className="mx-auto h-4 w-4"/></button></form></>:null}</main></div></div>;
}
function overdue(r:Conversation){return !r.first_response_at&&["open","pending"].includes(r.status)&&!!r.sla_due_at&&new Date(r.sla_due_at).getTime()<Date.now()}
function deadline(v:string){return v?new Date(v).toLocaleString("tr-TR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"—"}
function Summary({label,value,tone}:{label:string;value:number;tone:"cyan"|"rose"|"amber"}){const color={cyan:"text-cyan-200 border-cyan-400/20",rose:"text-rose-200 border-rose-400/20",amber:"text-amber-200 border-amber-400/20"}[tone];return <article className={`rounded-2xl border bg-white/[.025] p-4 ${color}`}><p className="text-[10px] font-black uppercase opacity-60">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></article>}
