export const P = {
  vet: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1400&q=80",
  vet2: "https://images.unsplash.com/photo-1576201836106-3ec7c41216d6?auto=format&fit=crop&w=1200&q=80",
  vet3: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1200&q=80",
  cake: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1400&q=80",
  cake2: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1200&q=80",
  cake3: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=1200&q=80",
  dry: "https://images.unsplash.com/photo-1545173164-22d1b201357c?auto=format&fit=crop&w=1400&q=80",
  dry2: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=1200&q=80",
  dry3: "https://images.unsplash.com/photo-1517677208171-0ec17a5c1cba?auto=format&fit=crop&w=1200&q=80",
  nalbur: "https://images.unsplash.com/photo-1504148458006-5492fbd32d1e?auto=format&fit=crop&w=1400&q=80",
  nalbur2: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&w=1200&q=80",
  tools: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=1400&q=80",
  tools2: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=1200&q=80",
  market: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80",
  market2: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
  hair: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1400&q=80",
  hair2: "https://images.unsplash.com/photo-1522337094846-8a818192de1f?auto=format&fit=crop&w=1200&q=80",
  gold: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1400&q=80",
  gold2: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1200&q=80",
  jewel: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1400&q=80",
  jewel2: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=80",
  boutique: "https://images.unsplash.com/photo-1441984904996-e0b6ba87e799?auto=format&fit=crop&w=1400&q=80",
  boutique2: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
  parts: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=1400&q=80",
  parts2: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
  code: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1400&q=80",
  code2: "https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1200&q=80",
  house: "https://images.unsplash.com/photo-1560518883-ce09059eeafa?auto=format&fit=crop&w=1400&q=80",
  house2: "https://images.unsplash.com/photo-1564010438633-4a36c2554b0d?auto=format&fit=crop&w=1200&q=80",
  house3: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
  resto: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=80",
  resto2: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",
  spice: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1400&q=80",
  spice2: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=1200&q=80",
  phone: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1400&q=80",
  phone2: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
  pc: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1400&q=80",
  pc2: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
  corp: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80",
  corp2: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
  law: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1400&q=80",
  law2: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80",
  app: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1400&q=80",
  app2: "https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1200&q=80",
} as const;

export type ExtraKind = "local" | "shop" | "pro";
export type ExtraWidget = "book" | "call" | "shop" | "menu" | "listing" | "software" | "app";

export type ExtraDemo = {
  slug: string;
  kind: ExtraKind;
  widget: ExtraWidget;
  title: string;
  brand: string;
  subtitle: string;
  accent: string;
  bg: string;
  hero: string;
  hook: string;
  lead: string;
  slides: { src: string; alt: string; caption: string }[];
  services: { t: string; d: string }[];
  products?: { name: string; price: string; img: string; tag?: string }[];
  listings?: { name: string; meta: string; price: string; img: string }[];
  menu?: { cat: string; name: string; price: string }[];
  choices: string[];
  reviews: { n: string; t: string }[];
  districts: string[];
};

const HATAY = ["Antakya", "Defne", "İskenderun", "Samandağ"];

export const EXTRA_DEMOS: ExtraDemo[] = [
  {
    slug: "veteriner",
    kind: "local",
    widget: "book",
    title: "Antakya Veteriner",
    brand: "Pati Veteriner",
    subtitle: "Aşı, muayene, pet otel — randevu aynı gün",
    accent: "#0d9488",
    bg: "#134e4a",
    hero: P.vet,
    hook: "Dostunuz hasta beklemesin. Aynı gün bakış.",
    lead: "Kedi, köpek, kuş. Aşı takvimi ve kısırlaştırma randevusu WhatsApp’tan.",
    slides: [
      { src: P.vet, alt: "Pet", caption: "Muayene" },
      { src: P.vet2, alt: "Klinik", caption: "Klinik" },
      { src: P.vet3, alt: "Dost", caption: "Pet otel" },
    ],
    services: [
      { t: "Aşı ve chip", d: "Takvim hatırlatılır. Kayıt deftere işlenir." },
      { t: "Muayene", d: "Aynı gün bakış. Acil gece hattı ayrı." },
      { t: "Pet otel", d: "Tatilde mama ve yürüyüş notu alınır." },
    ],
    choices: ["Aşı", "Muayene", "Kısırlaştırma", "Pet otel"],
    reviews: [
      { n: "Elif T.", t: "Kedimin aşı kartı düzgün tutuldu." },
      { n: "Burak S.", t: "Aynı gün bakış. Fiyat başta söylendi." },
    ],
    districts: HATAY,
  },
  {
    slug: "pastane",
    kind: "local",
    widget: "book",
    title: "Antakya Pastane",
    brand: "Defne Pastanesi",
    subtitle: "Yaş pasta siparişi, baklava, özel gün",
    accent: "#c2410c",
    bg: "#7c2d12",
    hero: P.cake,
    hook: "Doğum günü pastası. 24 saat önce sipariş yeter.",
    lead: "Yaş pasta, baklava, kurabiye. Yazılı sipariş, teslim saati net.",
    slides: [
      { src: P.cake, alt: "Pasta", caption: "Yaş pasta" },
      { src: P.cake2, alt: "Ekmek", caption: "Taze fırın" },
      { src: P.cake3, alt: "Cupcake", caption: "Özel gün" },
    ],
    services: [
      { t: "Yaş pasta", d: "İsim yazılır. Fotoğraflı onay gönderilir." },
      { t: "Baklava / künefe", d: "Kiloluk sipariş. Düğün tepsisi." },
      { t: "Kurumsal ikram", d: "Ofis kutusu. Sabah teslim." },
    ],
    choices: ["1 kg yaş pasta", "Nişan pastası", "Baklava kg", "Kurabiye kutu"],
    reviews: [
      { n: "Merve A.", t: "Pasta saatinde geldi, isim düzgündü." },
      { n: "Hakan D.", t: "Düğün tepsisi. Tat ve sunum iyi." },
    ],
    districts: HATAY,
  },
  {
    slug: "kuru-temizleme",
    kind: "local",
    widget: "call",
    title: "Hatay Kuru Temizleme",
    brand: "Ütü Evi",
    subtitle: "Takım, gelinlik, halı — al-teslim",
    accent: "#0369a1",
    bg: "#0c4a6e",
    hero: P.dry,
    hook: "Takımı bırak, ütülü teslim al. Mahalle servisi var.",
    lead: "Kuru temizleme, ütü, halı. Leke türü başta konuşulur.",
    slides: [
      { src: P.dry, alt: "Askı", caption: "Teslim" },
      { src: P.dry2, alt: "Çamaşır", caption: "Yıkama" },
      { src: P.dry3, alt: "Ütü", caption: "Ütü" },
    ],
    services: [
      { t: "Takım / gömlek", d: "Aynı gün ütü. Askıda teslim." },
      { t: "Gelinlik", d: "Özel leke. Teslim tarihi yazılı." },
      { t: "Halı", d: "Metrekare. Kurutma sonrası teslim." },
    ],
    choices: ["Al-götür servis", "Aynı gün ütü", "Halı", "Gelinlik"],
    reviews: [
      { n: "Selin K.", t: "Gömlekler askıda, kırışık yok." },
      { n: "Ali R.", t: "Halı leke çıktı. Fiyat m²." },
    ],
    districts: HATAY,
  },
  {
    slug: "nalbur",
    kind: "local",
    widget: "call",
    title: "Mahalle Nalbur",
    brand: "Usta Nalbur",
    subtitle: "Vida, boya, hortum, anahtar — hemen",
    accent: "#b45309",
    bg: "#78350f",
    hero: P.nalbur,
    hook: "Kırılan hortum, eksik vida. Mahalle nalburu.",
    lead: "Boya, vida, kilit, musluk. Fotoğraf at, doğru parçayı söyleyelim.",
    slides: [
      { src: P.nalbur, alt: "Alet", caption: "Tezgah" },
      { src: P.nalbur2, alt: "Vida", caption: "Vida / boya" },
      { src: P.tools, alt: "El aleti", caption: "El aleti" },
    ],
    services: [
      { t: "Vida & hırdavat ufak", d: "Adet. Yanlış ölçü değişir." },
      { t: "Boya", d: "Litre ve renk kartelası." },
      { t: "Anahtar", d: "Kopya aynı gün." },
    ],
    choices: ["Vida / dübel", "Boya", "Musluk", "Anahtar kopya"],
    reviews: [
      { n: "Kemal Y.", t: "Fotoğraftan musluk bildiler." },
      { n: "Ayşe N.", t: "Boya rengini karıştırıp verdiler." },
    ],
    districts: HATAY,
  },
  {
    slug: "hirdavat",
    kind: "local",
    widget: "shop",
    title: "Hatay Hırdavat",
    brand: "Pro Hırdavat",
    subtitle: "Matkap, iş güvenliği, toptan alet",
    accent: "#1d4ed8",
    bg: "#1e3a8a",
    hero: P.tools,
    hook: "Şantiye ve atölye. Markalı alet, faturalı.",
    lead: "Nalbur değil; matkap, taşlama, baret, toptan sipariş.",
    slides: [
      { src: P.tools, alt: "Matkap", caption: "Elektrikli alet" },
      { src: P.tools2, alt: "Takım", caption: "Takım çantası" },
      { src: P.nalbur, alt: "Atölye", caption: "Atölye" },
    ],
    services: [
      { t: "Elektrikli alet", d: "Bosch / Makita. Yedek uç." },
      { t: "İş güvenliği", d: "Baret, eldiven, ayakkabı." },
      { t: "Toptan", d: "Şantiye listesi. Fatura." },
    ],
    products: [
      { name: "Darbe matkap", price: "₺2.450", img: P.tools, tag: "Popüler" },
      { name: "Taşlama 115", price: "₺1.890", img: P.tools2 },
      { name: "Takım çantası 108 p.", price: "₺980", img: P.nalbur },
      { name: "Baret + eldiven set", price: "₺420", img: P.nalbur2 },
    ],
    choices: ["Matkap", "Taşlama", "İş güvenliği", "Toptan liste"],
    reviews: [
      { n: "Usta Mehmet", t: "Şantiye listesini aynı gün hazırladılar." },
      { n: "Caner B.", t: "Matkap faturalı, uç hediye." },
    ],
    districts: HATAY,
  },
  {
    slug: "market",
    kind: "local",
    widget: "call",
    title: "Semt Market",
    brand: "Köşe Market",
    subtitle: "Süt, ekmek, su — WhatsApp sipariş",
    accent: "#16a34a",
    bg: "#14532d",
    hero: P.market,
    hook: "Akşam ekmek bitti. Mahalle marketi kapıya bırakır.",
    lead: "Günlük ihtiyaç. Listeyi yaz, mahalle teslimi.",
    slides: [
      { src: P.market, alt: "Reyon", caption: "Reyon" },
      { src: P.market2, alt: "Kasa", caption: "Kasa" },
      { src: P.spice, alt: "Bakkal", caption: "Günlük" },
    ],
    services: [
      { t: "WhatsApp liste", d: "Süt, ekmek, su. Teslim saati." },
      { t: "Su damacana", d: "Kapıya. Boş değişimi." },
      { t: "Veresiye defter", d: "Kayıtlı mahalle müşteri." },
    ],
    choices: ["Ekmek + süt", "Damacana", "Temizlik", "Tam liste"],
    reviews: [
      { n: "Fatma S.", t: "Akşam 8’de liste attım, geldi." },
      { n: "Okan L.", t: "Su damacana düzenli." },
    ],
    districts: ["Antakya", "Defne"],
  },
  {
    slug: "kuafor",
    kind: "local",
    widget: "book",
    title: "Antakya Kuaför",
    brand: "Salon Defne",
    subtitle: "Kesim, boya, gelin — randevu saati",
    accent: "#db2777",
    bg: "#9d174d",
    hero: P.hair,
    hook: "Boya 2 saat. Gelin prova ayrı randevu.",
    lead: "Kadın kuaför. Saat kilitlenir, bekletilmez.",
    slides: [
      { src: P.hair, alt: "Salon", caption: "Salon" },
      { src: P.hair2, alt: "Kesim", caption: "Kesim / boya" },
      { src: P.boutique2, alt: "Stil", caption: "Gelin" },
    ],
    services: [
      { t: "Kesim", d: "45 dk. Fön dahil." },
      { t: "Boya / ombre", d: "Süre başta söylenir." },
      { t: "Gelin", d: "Prova + düğün günü." },
    ],
    choices: ["Kesim", "Boya", "Fön", "Gelin prova"],
    reviews: [
      { n: "Derya M.", t: "Randevu saatinde aldılar." },
      { n: "İpek Y.", t: "Gelin prova fotoğraflı netti." },
    ],
    districts: HATAY,
  },
  {
    slug: "kuyumcu",
    kind: "shop",
    widget: "shop",
    title: "Kuyumcu E-Ticaret",
    brand: "Antakya Altın",
    subtitle: "Gram, bilezik, set — online vitrin",
    accent: "#ca8a04",
    bg: "#713f12",
    hero: P.gold,
    hook: "Gram ve işçilik ayrı yazılır. Sahte vitrin değil.",
    lead: "E-ticaret kuyumcu örneği. Has, işçilik, kargo sigortalı.",
    slides: [
      { src: P.gold, alt: "Altın", caption: "Has altın" },
      { src: P.gold2, alt: "Yüzük", caption: "Yüzük" },
      { src: P.jewel, alt: "Kolye", caption: "Set" },
    ],
    services: [
      { t: "Gram altın", d: "Günlük kur. İşçilik satırda." },
      { t: "Bilezik / set", d: "Ayar yazılı. Kutu." },
      { t: "Kapora", d: "Online ön ödeme. Kargo sigorta." },
    ],
    products: [
      { name: "22 ayar bilezik", price: "İşçilik + has", img: P.gold, tag: "Vitrin" },
      { name: "Alyans çift", price: "Teklif", img: P.gold2 },
      { name: "Kolye set", price: "Teklif", img: P.jewel },
      { name: "Gram külçe", price: "Günlük kur", img: P.gold2, tag: "Kur" },
    ],
    choices: ["Gram", "Bilezik", "Alyans", "Set"],
    reviews: [
      { n: "Serkan A.", t: "İşçilik ve has ayrı faturada." },
      { n: "Gülşah T.", t: "Kargo sigortalı geldi." },
    ],
    districts: HATAY,
  },
  {
    slug: "taki",
    kind: "shop",
    widget: "shop",
    title: "Takı E-Ticaret",
    brand: "Nokta Takı",
    subtitle: "Çelik, gümüş, günlük takı satışı",
    accent: "#7c3aed",
    bg: "#4c1d95",
    hero: P.jewel,
    hook: "Sepete at, kapıda veya online öde. Stok görünür.",
    lead: "Takı e-ticaret örneği. Varyant: renk, ölçü.",
    slides: [
      { src: P.jewel, alt: "Kolye", caption: "Kolye" },
      { src: P.jewel2, alt: "Küpe", caption: "Küpe" },
      { src: P.gold2, alt: "Yüzük", caption: "Yüzük" },
    ],
    services: [
      { t: "Çelik koleksiyon", d: "Kararma yazılmaz, bakım notu var." },
      { t: "Gümüş", d: "925 damga. Kutu." },
      { t: "Kargo", d: "Hatay içi ertesi gün." },
    ],
    products: [
      { name: "Çelik kolye", price: "₺390", img: P.jewel, tag: "Çok satan" },
      { name: "Halka küpe", price: "₺240", img: P.jewel2 },
      { name: "Gümüş yüzük", price: "₺680", img: P.gold2 },
      { name: "Bileklik set", price: "₺520", img: P.jewel },
    ],
    choices: ["Kolye", "Küpe", "Yüzük", "Set"],
    reviews: [
      { n: "Ceren B.", t: "Ölçü tablosu doğruydu." },
      { n: "Nazlı K.", t: "Kutu ve kartla geldi." },
    ],
    districts: HATAY,
  },
  {
    slug: "butik",
    kind: "shop",
    widget: "shop",
    title: "Butik E-Ticaret",
    brand: "Defne Butik",
    subtitle: "Kadın giyim — beden, kumaş, iade",
    accent: "#e11d48",
    bg: "#9f1239",
    hero: P.boutique,
    hook: "Beden tablosu açık. İade 14 gün yazılı.",
    lead: "Butik e-ticaret. Fotoğraf gerçek ürün, stok adedi görünür.",
    slides: [
      { src: P.boutique, alt: "Mağaza", caption: "Mağaza" },
      { src: P.boutique2, alt: "Giyim", caption: "Yeni sezon" },
      { src: P.hair2, alt: "Stil", caption: "Kombin" },
    ],
    services: [
      { t: "Beden", d: "S–XL tablo. Model boyu yazılır." },
      { t: "İade", d: "14 gün. Etiket duracak." },
      { t: "Kapıda ödeme", d: "Hatay içi." },
    ],
    products: [
      { name: "Keten gömlek", price: "₺890", img: P.boutique, tag: "Yeni" },
      { name: "Pantolon", price: "₺1.140", img: P.boutique2 },
      { name: "Elbise", price: "₺1.690", img: P.boutique },
      { name: "Ceket", price: "₺2.240", img: P.boutique2 },
    ],
    choices: ["Gömlek", "Pantolon", "Elbise", "Ceket"],
    reviews: [
      { n: "Hilal S.", t: "Beden tablosu tuttu." },
      { n: "Ece P.", t: "İade sorunsuz oldu." },
    ],
    districts: HATAY,
  },
  {
    slug: "motor-parcasi",
    kind: "shop",
    widget: "shop",
    title: "Motor Parçası",
    brand: "Hatay Oto Parça",
    subtitle: "Yedek parça — marka, şasi, kargo",
    accent: "#111827",
    bg: "#030712",
    hero: P.parts,
    hook: "Şasi no yaz. Yanlış parça gitmesin.",
    lead: "Oto / motor yedek. OEM kodu ve uyumluluk satırda.",
    slides: [
      { src: P.parts, alt: "Atölye", caption: "Parça" },
      { src: P.parts2, alt: "Araç", caption: "Uyum" },
      { src: P.tools2, alt: "Depo", caption: "Stok" },
    ],
    services: [
      { t: "Şasi sorgu", d: "Fotoğraf + model yılı." },
      { t: "OEM kod", d: "Eşdeğer alternatif yazılı." },
      { t: "Kargo", d: "Aynı gün kesiğe kadar." },
    ],
    products: [
      { name: "Fren balata set", price: "₺1.280", img: P.parts, tag: "Stokta" },
      { name: "Yağ filtresi", price: "₺240", img: P.parts2 },
      { name: "Amortisör", price: "₺2.150", img: P.tools },
      { name: "Far (sağ)", price: "Teklif", img: P.parts2 },
    ],
    choices: ["Fren", "Filtre", "Elektrik", "Kaporta"],
    reviews: [
      { n: "Usta Rıza", t: "Şasiden doğru balata geldi." },
      { n: "Emre C.", t: "Far OEM kodu faturada." },
    ],
    districts: HATAY,
  },
  {
    slug: "ozel-yazilim",
    kind: "pro",
    widget: "software",
    title: "Özel Yazılım",
    brand: "Hatay360 Yazılım",
    subtitle: "Sipariş, stok, randevu — size özel panel",
    accent: "#00a8c4",
    bg: "#071b22",
    hero: P.code,
    hook: "Hazır paket yetmeyince özel panel yazılır.",
    lead: "KOBİ yazılımı. Lisanslı BUNG değil; işletmenize göre ekran.",
    slides: [
      { src: P.code, alt: "Kod", caption: "Geliştirme" },
      { src: P.code2, alt: "Panel", caption: "Panel" },
      { src: P.corp2, alt: "Ekip", caption: "Keşif" },
    ],
    services: [
      { t: "Keşif", d: "Süreç çizilir. Abartı yok." },
      { t: "Modül", d: "Sipariş, stok, randevu, rapor." },
      { t: "Teslim", d: "Eğitim + 30 gün düzeltme." },
    ],
    choices: ["Sipariş paneli", "Randevu", "Saha ekibi", "Entegrasyon"],
    reviews: [
      { n: "Atölye sahibi", t: "Excel bitti, panel duruyor." },
      { n: "Depo sorumlu", t: "Stok hareketi görünür oldu." },
    ],
    districts: ["Uzaktan / Hatay"],
  },
  {
    slug: "emlak",
    kind: "pro",
    widget: "listing",
    title: "Emlak Ofisi",
    brand: "Antakya Emlak",
    subtitle: "Satılık / kiralık — ilan, m², oda",
    accent: "#0369a1",
    bg: "#0c4a6e",
    hero: P.house,
    hook: "İlan gerçek fotoğraf. m² ve aidat yazılı.",
    lead: "Emlak vitrini. Portföy, filtre, randevulu gezi.",
    slides: [
      { src: P.house, alt: "Ev", caption: "Satılık" },
      { src: P.house2, alt: "Villa", caption: "Villa" },
      { src: P.house3, alt: "Daire", caption: "Daire" },
    ],
    services: [
      { t: "Satılık", d: "Tapu ve iskan notu." },
      { t: "Kiralık", d: "Depozito ve aidat ayrı." },
      { t: "Gezi", d: "Randevu. Anahtar ofiste." },
    ],
    listings: [
      { name: "Defne 3+1", meta: "145 m² · 3. kat · asansör", price: "₺4.250.000", img: P.house },
      { name: "Antakya 2+1 kiralık", meta: "95 m² · eşyalı", price: "₺18.500 / ay", img: P.house2 },
      { name: "İskenderun villa", meta: "220 m² · bahçe", price: "Teklif", img: P.house3 },
      { name: "Samandağ yazlık", meta: "Denize 800 m", price: "₺6.900.000", img: P.house2 },
    ],
    choices: ["Satılık daire", "Kiralık", "Arsa", "İşyeri"],
    reviews: [
      { n: "Mehmet K.", t: "İlandaki m² yerinde tuttu." },
      { n: "Selin A.", t: "Gezi randevusu saatindeydi." },
    ],
    districts: HATAY,
  },
  {
    slug: "restoran",
    kind: "local",
    widget: "menu",
    title: "Restoran",
    brand: "Asmalı Mutfak",
    subtitle: "Menü, rezervasyon, paket servis",
    accent: "#b45309",
    bg: "#431407",
    hero: P.resto,
    hook: "Rezervasyon saati. Menü güncel, stok biteni çizeriz.",
    lead: "Restoran sitesi. Menü, masa, paket. Abartılı yıldız yok.",
    slides: [
      { src: P.resto, alt: "Salon", caption: "Salon" },
      { src: P.resto2, alt: "Tabak", caption: "Mutfak" },
      { src: P.cake2, alt: "Tatlı", caption: "Tatlı" },
    ],
    services: [
      { t: "Rezervasyon", d: "Kişi sayısı + saat." },
      { t: "Paket", d: "WhatsApp. Teslim aralığı." },
      { t: "Menü", d: "Günlük çorba ayrı." },
    ],
    menu: [
      { cat: "Başlangıç", name: "Humus", price: "₺120" },
      { cat: "Başlangıç", name: "İçli köfte", price: "₺160" },
      { cat: "Ana", name: "Künefe hariç kebap porsiyon", price: "₺420" },
      { cat: "Ana", name: "Izgara karışık", price: "₺580" },
      { cat: "Tatlı", name: "Künefe", price: "₺180" },
      { cat: "İçecek", name: "Ayran / şalgam", price: "₺40" },
    ],
    choices: ["2 kişilik masa", "4 kişilik", "Paket", "Özel gün"],
    reviews: [
      { n: "Hakan Y.", t: "Rezervasyon tutuldu, bekletilmedik." },
      { n: "Lale T.", t: "Paket saatinde, sıcak." },
    ],
    districts: HATAY,
  },
  {
    slug: "aktar",
    kind: "local",
    widget: "shop",
    title: "Aktar & Baharat",
    brand: "Çarşı Aktar",
    subtitle: "Baharat, çay, aktariye — kg",
    accent: "#c2410c",
    bg: "#7c2d12",
    hero: P.spice,
    hook: "Sumak, isot, zahter. Kg ve paket net.",
    lead: "Aktar vitrini. Baharat taze çekim, tarih yazılı.",
    slides: [
      { src: P.spice, alt: "Baharat", caption: "Baharat" },
      { src: P.market, alt: "Çarşı", caption: "Çarşı" },
      { src: P.cake3, alt: "Çay", caption: "Çay / aktar" },
    ],
    services: [
      { t: "Baharat kg", d: "Isot, sumak, karabiber." },
      { t: "Çay", d: "Dökme. Tadım yok, koku var." },
      { t: "Aktariye", d: "Bitki çayı. Tavsiye abartısız." },
    ],
    products: [
      { name: "Hatay isot 250 g", price: "₺95", img: P.spice, tag: "Yerel" },
      { name: "Zahter", price: "₺80", img: P.spice2 },
      { name: "Sumak", price: "₺70", img: P.spice },
      { name: "Karışık baharat set", price: "₺240", img: P.market2 },
    ],
    choices: ["Isot", "Zahter", "Çay", "Set"],
    reviews: [
      { n: "Ayşe T.", t: "Isot taze, paket gramaj tuttu." },
      { n: "Cemil D.", t: "Set hediyelik güzel." },
    ],
    districts: HATAY,
  },
  {
    slug: "telefoncu",
    kind: "local",
    widget: "call",
    title: "Telefoncu",
    brand: "Ekran Tamir",
    subtitle: "Ekran, batarya, ikinci el — süre net",
    accent: "#2563eb",
    bg: "#1e3a8a",
    hero: P.phone,
    hook: "Ekran kaç saatte biter, başta söylenir.",
    lead: "Telefon tamir + ikinci el. Yedek parça orijinal/eşdeğer yazılır.",
    slides: [
      { src: P.phone, alt: "Telefon", caption: "Cihaz" },
      { src: P.phone2, alt: "Tamir", caption: "Tamir" },
      { src: P.pc2, alt: "Tezgah", caption: "Tezgah" },
    ],
    services: [
      { t: "Ekran", d: "Model + süre + fiyat." },
      { t: "Batarya", d: "Şişme kontrol. Garanti süre." },
      { t: "İkinci el", d: "İmei ve kutu notu." },
    ],
    choices: ["Ekran", "Batarya", "Şarj soketi", "İkinci el"],
    reviews: [
      { n: "Onur P.", t: "Ekran 2 saatte. Eşdeğer yazdılar." },
      { n: "Mert A.", t: "İkinci elde iMei gösterdiler." },
    ],
    districts: HATAY,
  },
  {
    slug: "bilgisayarci",
    kind: "local",
    widget: "call",
    title: "Bilgisayarcı",
    brand: "Hatay PC",
    subtitle: "Format, laptop, toplayıcı sistem",
    accent: "#4f46e5",
    bg: "#312e81",
    hero: P.pc,
    hook: "Format + yedek. Laptop ısınma ayrı teşhis.",
    lead: "Bilgisayar tamir ve satış. Parça faturalı.",
    slides: [
      { src: P.pc, alt: "Laptop", caption: "Laptop" },
      { src: P.pc2, alt: "Kart", caption: "Donanım" },
      { src: P.code, alt: "Masabaşı", caption: "Servis" },
    ],
    services: [
      { t: "Format", d: "Yedek alınır. Lisans konuşulur." },
      { t: "Laptop", d: "Ekran, batarya, fan." },
      { t: "Toplama", d: "Liste + fatura." },
    ],
    choices: ["Format", "Fan / pasta", "RAM / SSD", "Toplama liste"],
    reviews: [
      { n: "Berk U.", t: "SSD takıp Windows’u onlar kurdu." },
      { n: "Zeynep H.", t: "Isınma pasta ile düzeldi." },
    ],
    districts: HATAY,
  },
  {
    slug: "kurumsal",
    kind: "pro",
    widget: "call",
    title: "Kurumsal Firma",
    brand: "Hatay Endüstri",
    subtitle: "B2B vitrin — üretim, kalite, teklif",
    accent: "#0f766e",
    bg: "#134e4a",
    hero: P.corp,
    hook: "Fabrikayı anlatan site. Teklif formu, kalite belgeleri.",
    lead: "Kurumsal web. Hakkımızda şişirme değil; kapasite ve referans.",
    slides: [
      { src: P.corp, alt: "Bina", caption: "Tesis" },
      { src: P.corp2, alt: "Ofis", caption: "Ofis" },
      { src: P.code2, alt: "İş", caption: "Üretim" },
    ],
    services: [
      { t: "Üretim", d: "Kapasite ve teslim süresi." },
      { t: "Kalite", d: "Belge PDF. Sahte rozet yok." },
      { t: "Teklif", d: "B2B form. Yetkili mail." },
    ],
    choices: ["Ürün kataloğu", "Teklif", "Ziyaret", "İnsan kaynakları"],
    reviews: [
      { n: "Satın alma", t: "Teklif formu işe yaradı." },
      { n: "İş ortağı", t: "Tesis fotoğrafları gerçekçi." },
    ],
    districts: ["Hatay / ihracat"],
  },
  {
    slug: "avukat",
    kind: "pro",
    widget: "book",
    title: "Hukuk Bürosu",
    brand: "Av. Ofisi",
    subtitle: "Danışma randevusu — aile, icra, ticaret",
    accent: "#1e3a5f",
    bg: "#0f172a",
    hero: P.law,
    hook: "İlk görüşme randevulu. Dosya WhatsApp’tan değil, ofiste.",
    lead: "Avukat sitesi. Uzmanlık alanları net. Sonuç vaadi yok.",
    slides: [
      { src: P.law, alt: "Hukuk", caption: "Bürosu" },
      { src: P.law2, alt: "Görüşme", caption: "Görüşme" },
      { src: P.corp2, alt: "Ofis", caption: "Ofis" },
    ],
    services: [
      { t: "Aile / boşanma", d: "Randevu. Belge listesi." },
      { t: "İcra", d: "Dosya inceleme ücreti başta." },
      { t: "Ticaret", d: "Sözleşme ve şirket." },
    ],
    choices: ["İlk danışma", "İcra", "Aile", "Ticaret"],
    reviews: [
      { n: "Müvekkil A.", t: "Randevu saati tutuldu." },
      { n: "Şirket yetkilisi", t: "Sözleşme taslağı netti." },
    ],
    districts: ["Antakya", "İskenderun"],
  },
  {
    slug: "mobil-uygulama",
    kind: "pro",
    widget: "app",
    title: "Mobil Uygulama",
    brand: "Hatay360 Apps",
    subtitle: "Android & iOS — size özel uygulama",
    accent: "#00a8c4",
    bg: "#071b22",
    hero: P.app,
    hook: "Mağaza ikonu, bildirim, üye girişi. Web sitesi değil; uygulama.",
    lead: "Özel mobil yazılım örneği. Android ve iOS. Store yayın süreci ayrıca.",
    slides: [
      { src: P.app, alt: "Telefon", caption: "iOS / Android" },
      { src: P.app2, alt: "UI", caption: "Arayüz" },
      { src: P.code2, alt: "Geliştirme", caption: "Geliştirme" },
    ],
    services: [
      { t: "Keşif", d: "Ekran listesi. Native / çapraz." },
      { t: "Yayın", d: "Play / App Store hesapları sizde." },
      { t: "Bildirim", d: "Kampanya ve randevu hatırlatma." },
    ],
    choices: ["Sipariş uygulaması", "Randevu", "Saha ekibi", "Üye kulübü"],
    reviews: [
      { n: "Restoran işletmesi", t: "Paket uygulaması sade kaldı." },
      { n: "Klinik", t: "Randevu bildirimi işe yaradı." },
    ],
    districts: ["Uzaktan / Hatay"],
  },
];

export const EXTRA_GROUPS: { id: ExtraKind; title: string; text: string }[] = [
  { id: "local", title: "Yerel işletme siteleri", text: "Veteriner, pastane, kuaför, market, tamir — çağrı ve randevu." },
  { id: "shop", title: "E-ticaret örnekleri", text: "Kuyumcu, takı, butik, hırdavat, motor parçası." },
  { id: "pro", title: "Kurumsal, emlak, yazılım, mobil", text: "Firma vitrini, hukuk, özel yazılım ve Android / iOS." },
];

export function extraBySlug(slug: string) {
  return EXTRA_DEMOS.find((d) => d.slug === slug);
}
