export const P = {
  vet: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1400&q=80",
  vet2: "https://images.unsplash.com/photo-1576201836106-3ec7c41216d6?auto=format&fit=crop&w=1200&q=80",
  vet3: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1200&q=80",
  cake: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1400&q=80",
  cake2: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1200&q=80",
  cake3: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=1200&q=80",
  dry: "https://images.unsplash.com/photo-1545173164-22d1b201357c?auto=format&fit=crop&w=1400&q=80",
  dry2: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=1200&q=80",
  dry3: "https://images.unsplash.com/photo-1517677208171-0ec17a5c1cba?auto=format&fit=crop&w=1200&q=80",
  nalbur: "https://images.unsplash.com/photo-1504148458006-5492fbd32d1e?auto=format&fit=crop&w=1400&q=80",
  nalbur2: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&w=1200&q=80",
  tools: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=1400&q=80",
  tools2: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=1200&q=80",
  market: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80",
  market2: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
  meat: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=1400&q=80",
  meat2: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1200&q=80",
  gym: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=80",
  gym2: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=1200&q=80",
  hair: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1400&q=80",
  hair2: "https://images.unsplash.com/photo-1522337094846-8a818192de1f?auto=format&fit=crop&w=1200&q=80",
  barber: "https://images.unsplash.com/photo-1503951914875-834188fe4720?auto=format&fit=crop&w=1400&q=80",
  barber2: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=80",
  gold: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1400&q=80",
  gold2: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1200&q=80",
  jewel: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1400&q=80",
  jewel2: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=80",
  boutique: "https://images.unsplash.com/photo-1441984904996-e0b6ba87e799?auto=format&fit=crop&w=1400&q=80",
  boutique2: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
  parts: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=1400&q=80",
  parts2: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
  code: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1400&q=80",
  code2: "https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1200&q=80",
  house: "https://images.unsplash.com/photo-1560518883-ce09059eeafa?auto=format&fit=crop&w=1400&q=80",
  house2: "https://images.unsplash.com/photo-1564010438633-4a36c2554b0d?auto=format&fit=crop&w=1200&q=80",
  house3: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
  resto: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=80",
  resto2: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",
  spice: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1400&q=80",
  spice2: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=1200&q=80",
  produce: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1400&q=80",
  phone: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1400&q=80",
  phone2: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
  pc: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1400&q=80",
  pc2: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
  corp: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80",
  corp2: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
  law: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1400&q=80",
  law2: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80",
  app: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1400&q=80",
  app2: "https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1200&q=80",
  pharm: "https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=1400&q=80",
  pharm2: "https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=1200&q=80",
  wash: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=1400&q=80",
  wash2: "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?auto=format&fit=crop&w=1200&q=80",
  wedding: "https://images.unsplash.com/photo-1519167758481-83f29da81c46?auto=format&fit=crop&w=1400&q=80",
  wedding2: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80",
  bread: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1400&q=80",
  bread2: "https://images.unsplash.com/photo-1549931319-a545dcf3d7a9?auto=format&fit=crop&w=1200&q=80",
  flower: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1400&q=80",
  flower2: "https://images.unsplash.com/photo-1457089328109-07c3c792c9d0?auto=format&fit=crop&w=1200&q=80",
  dental: "https://images.unsplash.com/photo-1606811841689-23dfddceee33?auto=format&fit=crop&w=1400&q=80",
  dental2: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80",
  glasses: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&w=1400&q=80",
  glasses2: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1200&q=80",
  coffee: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1400&q=80",
  coffee2: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
  tire: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=1400&q=80",
  tire2: "https://images.unsplash.com/photo-1619642751034-085acef54fe8?auto=format&fit=crop&w=1200&q=80",
  pet: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=1400&q=80",
  pet2: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80",
  photo: "https://images.unsplash.com/photo-1471341971476-ae15ff5dd4ea?auto=format&fit=crop&w=1400&q=80",
  photo2: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80",
  desk: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1400&q=80",
  desk2: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
  class: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1400&q=80",
  class2: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&w=1200&q=80",
  ac: "https://images.unsplash.com/photo-1631545806609-34ed2f0f4a4b?auto=format&fit=crop&w=1400&q=80",
  ac2: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=80",
  pipe: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=1400&q=80",
  pipe2: "https://images.unsplash.com/photo-1504148458006-5492fbd32d1e?auto=format&fit=crop&w=1200&q=80",
  hotel: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=80",
  hotel2: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
  olive: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1400&q=80",
  olive2: "https://images.unsplash.com/photo-1471943311424-646960669fbc?auto=format&fit=crop&w=1200&q=80",
  dish: "https://images.unsplash.com/photo-1556912172-45b7abe8b7c1?auto=format&fit=crop&w=1400&q=80",
  dish2: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1200&q=80",
  glass: "https://images.unsplash.com/photo-1513558161293-cdaf765d22c7?auto=format&fit=crop&w=1200&q=80",
  rug: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1400&q=80",
  rug2: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1200&q=80",
  dessert: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1400&q=80",
  sofa: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=80",
  sofa2: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80",
  shoe: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1400&q=80",
  shoe2: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=1200&q=80",
} as const;

export type ExtraKind = "local" | "shop" | "pro";
export type ExtraWidget = "book" | "call" | "shop" | "menu" | "listing" | "software" | "app";

export type ExtraDemo = {
  slug: string;
  kind: ExtraKind;
  widget: ExtraWidget;
  title: string;
  brand: string;
  subtitle: string;
  accent: string;
  bg: string;
  hero: string;
  hook: string;
  lead: string;
  slides: { src: string; alt: string; caption: string }[];
  services: { t: string; d: string }[];
  products?: { name: string; price: string; img: string; tag?: string }[];
  listings?: { name: string; meta: string; price: string; img: string }[];
  menu?: { cat: string; name: string; price: string }[];
  choices: string[];
  reviews: { n: string; t: string }[];
  districts: string[];
};

const HATAY = ["Antakya", "Defne", "İskenderun", "Samandağ"];

export const EXTRA_DEMOS: ExtraDemo[] = [
  {
    slug: "veteriner",
    kind: "local",
    widget: "book",
    title: "Antakya Veteriner",
    brand: "Pati Veteriner",
    subtitle: "Aşı, muayene, pet otel — randevu aynı gün",
    accent: "#0d9488",
    bg: "#134e4a",
    hero: P.vet,
    hook: "Dostunuz hasta beklemesin. Aynı gün bakış.",
    lead: "Kedi, köpek, kuş. Aşı takvimi ve kısırlaştırma randevusu WhatsApp’tan.",
    slides: [
      { src: P.vet, alt: "Pet", caption: "Muayene" },
      { src: P.vet2, alt: "Klinik", caption: "Klinik" },
      { src: P.vet3, alt: "Dost", caption: "Pet otel" },
    ],
    services: [
      { t: "Aşı ve chip", d: "Takvim hatırlatılır. Kayıt deftere işlenir." },
      { t: "Muayene", d: "Aynı gün bakış. Acil gece hattı ayrı." },
      { t: "Pet otel", d: "Tatilde mama ve yürüyüş notu alınır." },
    ],
    choices: ["Aşı", "Muayene", "Kısırlaştırma", "Pet otel"],
    reviews: [
      { n: "Elif T.", t: "Kedimin aşı kartı düzgün tutuldu." },
      { n: "Burak S.", t: "Aynı gün bakış. Fiyat başta söylendi." },
    ],
    districts: HATAY,
  },
  {
    slug: "pastane",
    kind: "local",
    widget: "book",
    title: "Antakya Pastane",
    brand: "Defne Pastanesi",
    subtitle: "Yaş pasta siparişi, baklava, özel gün",
    accent: "#c2410c",
    bg: "#7c2d12",
    hero: P.cake,
    hook: "Doğum günü pastası. 24 saat önce sipariş yeter.",
    lead: "Yaş pasta, baklava, kurabiye. Yazılı sipariş, teslim saati net.",
    slides: [
      { src: P.cake, alt: "Pasta", caption: "Yaş pasta" },
      { src: P.cake2, alt: "Ekmek", caption: "Taze fırın" },
      { src: P.cake3, alt: "Cupcake", caption: "Özel gün" },
    ],
    services: [
      { t: "Yaş pasta", d: "İsim yazılır. Fotoğraflı onay gönderilir." },
      { t: "Baklava / künefe", d: "Kiloluk sipariş. Düğün tepsisi." },
      { t: "Kurumsal ikram", d: "Ofis kutusu. Sabah teslim." },
    ],
    choices: ["1 kg yaş pasta", "Nişan pastası", "Baklava kg", "Kurabiye kutu"],
    reviews: [
      { n: "Merve A.", t: "Pasta saatinde geldi, isim düzgündü." },
      { n: "Hakan D.", t: "Düğün tepsisi. Tat ve sunum iyi." },
    ],
    districts: HATAY,
  },
  {
    slug: "kuru-temizleme",
    kind: "local",
    widget: "call",
    title: "Hatay Kuru Temizleme",
    brand: "Ütü Evi",
    subtitle: "Takım, gelinlik, halı — al-teslim",
    accent: "#0369a1",
    bg: "#0c4a6e",
    hero: P.dry,
    hook: "Takımı bırak, ütülü teslim al. Mahalle servisi var.",
    lead: "Kuru temizleme, ütü, halı. Leke türü başta konuşulur.",
    slides: [
      { src: P.dry, alt: "Askı", caption: "Teslim" },
      { src: P.dry2, alt: "Çamaşır", caption: "Yıkama" },
      { src: P.dry3, alt: "Ütü", caption: "Ütü" },
    ],
    services: [
      { t: "Takım / gömlek", d: "Aynı gün ütü. Askıda teslim." },
      { t: "Gelinlik", d: "Özel leke. Teslim tarihi yazılı." },
      { t: "Halı", d: "Metrekare. Kurutma sonrası teslim." },
    ],
    choices: ["Al-götür servis", "Aynı gün ütü", "Halı", "Gelinlik"],
    reviews: [
      { n: "Selin K.", t: "Gömlekler askıda, kırışık yok." },
      { n: "Ali R.", t: "Halı leke çıktı. Fiyat m²." },
    ],
    districts: HATAY,
  },
  {
    slug: "nalbur",
    kind: "local",
    widget: "call",
    title: "Mahalle Nalbur",
    brand: "Usta Nalbur",
    subtitle: "Vida, boya, hortum, anahtar — hemen",
    accent: "#b45309",
    bg: "#78350f",
    hero: P.nalbur,
    hook: "Kırılan hortum, eksik vida. Mahalle nalburu.",
    lead: "Boya, vida, kilit, musluk. Fotoğraf at, doğru parçayı söyleyelim.",
    slides: [
      { src: P.nalbur, alt: "Alet", caption: "Tezgah" },
      { src: P.nalbur2, alt: "Vida", caption: "Vida / boya" },
      { src: P.tools, alt: "El aleti", caption: "El aleti" },
    ],
    services: [
      { t: "Vida & hırdavat ufak", d: "Adet. Yanlış ölçü değişir." },
      { t: "Boya", d: "Litre ve renk kartelası." },
      { t: "Anahtar", d: "Kopya aynı gün." },
    ],
    choices: ["Vida / dübel", "Boya", "Musluk", "Anahtar kopya"],
    reviews: [
      { n: "Kemal Y.", t: "Fotoğraftan musluk bildiler." },
      { n: "Ayşe N.", t: "Boya rengini karıştırıp verdiler." },
    ],
    districts: HATAY,
  },
  {
    slug: "hirdavat",
    kind: "local",
    widget: "shop",
    title: "Hatay Hırdavat",
    brand: "Pro Hırdavat",
    subtitle: "Matkap, iş güvenliği, toptan alet",
    accent: "#1d4ed8",
    bg: "#1e3a8a",
    hero: P.tools,
    hook: "Şantiye ve atölye. Markalı alet, faturalı.",
    lead: "Nalbur değil; matkap, taşlama, baret, toptan sipariş.",
    slides: [
      { src: P.tools, alt: "Matkap", caption: "Elektrikli alet" },
      { src: P.tools2, alt: "Takım", caption: "Takım çantası" },
      { src: P.nalbur, alt: "Atölye", caption: "Atölye" },
    ],
    services: [
      { t: "Elektrikli alet", d: "Bosch / Makita. Yedek uç." },
      { t: "İş güvenliği", d: "Baret, eldiven, ayakkabı." },
      { t: "Toptan", d: "Şantiye listesi. Fatura." },
    ],
    products: [
      { name: "Darbe matkap", price: "₺2.450", img: P.tools, tag: "Popüler" },
      { name: "Taşlama 115", price: "₺1.890", img: P.tools2 },
      { name: "Takım çantası 108 p.", price: "₺980", img: P.nalbur },
      { name: "Baret + eldiven set", price: "₺420", img: P.nalbur2 },
    ],
    choices: ["Matkap", "Taşlama", "İş güvenliği", "Toptan liste"],
    reviews: [
      { n: "Usta Mehmet", t: "Şantiye listesini aynı gün hazırladılar." },
      { n: "Caner B.", t: "Matkap faturalı, uç hediye." },
    ],
    districts: HATAY,
  },
  {
    slug: "market",
    kind: "local",
    widget: "call",
    title: "Semt Market",
    brand: "Köşe Market",
    subtitle: "Süt, ekmek, su — WhatsApp sipariş",
    accent: "#16a34a",
    bg: "#14532d",
    hero: P.market,
    hook: "Akşam ekmek bitti. Mahalle marketi kapıya bırakır.",
    lead: "Günlük ihtiyaç. Listeyi yaz, mahalle teslimi.",
    slides: [
      { src: P.market, alt: "Reyon", caption: "Reyon" },
      { src: P.market2, alt: "Kasa", caption: "Kasa" },
      { src: P.spice, alt: "Bakkal", caption: "Günlük" },
    ],
    services: [
      { t: "WhatsApp liste", d: "Süt, ekmek, su. Teslim saati." },
      { t: "Su damacana", d: "Kapıya. Boş değişimi." },
      { t: "Veresiye defter", d: "Kayıtlı mahalle müşteri." },
    ],
    choices: ["Ekmek + süt", "Damacana", "Temizlik", "Tam liste"],
    reviews: [
      { n: "Fatma S.", t: "Akşam 8’de liste attım, geldi." },
      { n: "Okan L.", t: "Su damacana düzenli." },
    ],
    districts: ["Antakya", "Defne"],
  },
  {
    slug: "kuafor",
    kind: "local",
    widget: "book",
    title: "Antakya Kuaför",
    brand: "Salon Defne",
    subtitle: "Kesim, boya, gelin — randevu saati",
    accent: "#db2777",
    bg: "#9d174d",
    hero: P.hair,
    hook: "Boya 2 saat. Gelin prova ayrı randevu.",
    lead: "Kadın kuaför. Saat kilitlenir, bekletilmez.",
    slides: [
      { src: P.hair, alt: "Salon", caption: "Salon" },
      { src: P.hair2, alt: "Kesim", caption: "Kesim / boya" },
      { src: P.boutique2, alt: "Stil", caption: "Gelin" },
    ],
    services: [
      { t: "Kesim", d: "45 dk. Fön dahil." },
      { t: "Boya / ombre", d: "Süre başta söylenir." },
      { t: "Gelin", d: "Prova + düğün günü." },
    ],
    choices: ["Kesim", "Boya", "Fön", "Gelin prova"],
    reviews: [
      { n: "Derya M.", t: "Randevu saatinde aldılar." },
      { n: "İpek Y.", t: "Gelin prova fotoğraflı netti." },
    ],
    districts: HATAY,
  },
  {
    slug: "berber",
    kind: "local",
    widget: "book",
    title: "Erkek berber",
    brand: "Antakya Traş",
    subtitle: "Traş, sakal, randevu saati",
    accent: "#1d4ed8",
    bg: "#1e3a8a",
    hero: P.barber,
    hook: "Sıra bekleme. Traş 25 dk; saat kilitlenir.",
    lead: "Erkek berber sitesi. Kuaförden ayrı: traş, sakal, çocuk. WhatsApp’tan saat alınır.",
    slides: [
      { src: P.barber, alt: "Traş", caption: "Traş" },
      { src: P.barber2, alt: "Sakal", caption: "Sakal" },
      { src: P.hair, alt: "Salon", caption: "Koltuk" },
    ],
    services: [
      { t: "Traş", d: "25 dk. Makine / ustura." },
      { t: "Sakal", d: "Çizgi + bakım." },
      { t: "Çocuk", d: "Ayrı koltuk." },
    ],
    choices: ["Traş", "Sakal", "Çocuk", "Damat"],
    reviews: [
      { n: "Mehmet, Defne", t: "Randevu saatinde oturdum." },
      { n: "Ali, Antakya", t: "Sıra yok, süre yazılı." },
    ],
    districts: HATAY,
  },
  {
    slug: "kuyumcu",
    kind: "shop",
    widget: "shop",
    title: "Kuyumcu E-Ticaret",
    brand: "Antakya Altın",
    subtitle: "Gram, bilezik, set — online vitrin",
    accent: "#ca8a04",
    bg: "#713f12",
    hero: P.gold,
    hook: "Gram ve işçilik ayrı yazılır. Sahte vitrin değil.",
    lead: "E-ticaret kuyumcu örneği. Has, işçilik, kargo sigortalı.",
    slides: [
      { src: P.gold, alt: "Altın", caption: "Has altın" },
      { src: P.gold2, alt: "Yüzük", caption: "Yüzük" },
      { src: P.jewel, alt: "Kolye", caption: "Set" },
    ],
    services: [
      { t: "Gram altın", d: "Günlük kur. İşçilik satırda." },
      { t: "Bilezik / set", d: "Ayar yazılı. Kutu." },
      { t: "Kapora", d: "Online ön ödeme. Kargo sigorta." },
    ],
    products: [
      { name: "22 ayar bilezik", price: "İşçilik + has", img: P.gold, tag: "Vitrin" },
      { name: "Alyans çift", price: "Teklif", img: P.gold2 },
      { name: "Kolye set", price: "Teklif", img: P.jewel },
      { name: "Gram külçe", price: "Günlük kur", img: P.gold2, tag: "Kur" },
    ],
    choices: ["Gram", "Bilezik", "Alyans", "Set"],
    reviews: [
      { n: "Serkan A.", t: "İşçilik ve has ayrı faturada." },
      { n: "Gülşah T.", t: "Kargo sigortalı geldi." },
    ],
    districts: HATAY,
  },
  {
    slug: "taki",
    kind: "shop",
    widget: "shop",
    title: "Takı E-Ticaret",
    brand: "Nokta Takı",
    subtitle: "Çelik, gümüş, günlük takı satışı",
    accent: "#7c3aed",
    bg: "#4c1d95",
    hero: P.jewel,
    hook: "Sepete at, kapıda veya online öde. Stok görünür.",
    lead: "Takı e-ticaret örneği. Varyant: renk, ölçü.",
    slides: [
      { src: P.jewel, alt: "Kolye", caption: "Kolye" },
      { src: P.jewel2, alt: "Küpe", caption: "Küpe" },
      { src: P.gold2, alt: "Yüzük", caption: "Yüzük" },
    ],
    services: [
      { t: "Çelik koleksiyon", d: "Kararma yazılmaz, bakım notu var." },
      { t: "Gümüş", d: "925 damga. Kutu." },
      { t: "Kargo", d: "Hatay içi ertesi gün." },
    ],
    products: [
      { name: "Çelik kolye", price: "₺390", img: P.jewel, tag: "Çok satan" },
      { name: "Halka küpe", price: "₺240", img: P.jewel2 },
      { name: "Gümüş yüzük", price: "₺680", img: P.gold2 },
      { name: "Bileklik set", price: "₺520", img: P.jewel },
    ],
    choices: ["Kolye", "Küpe", "Yüzük", "Set"],
    reviews: [
      { n: "Ceren B.", t: "Ölçü tablosu doğruydu." },
      { n: "Nazlı K.", t: "Kutu ve kartla geldi." },
    ],
    districts: HATAY,
  },
  {
    slug: "butik",
    kind: "shop",
    widget: "shop",
    title: "Butik E-Ticaret",
    brand: "Defne Butik",
    subtitle: "Kadın giyim — beden, kumaş, iade",
    accent: "#e11d48",
    bg: "#9f1239",
    hero: P.boutique,
    hook: "Beden tablosu açık. İade 14 gün yazılı.",
    lead: "Butik e-ticaret. Fotoğraf gerçek ürün, stok adedi görünür.",
    slides: [
      { src: P.boutique, alt: "Mağaza", caption: "Mağaza" },
      { src: P.boutique2, alt: "Giyim", caption: "Yeni sezon" },
      { src: P.hair2, alt: "Stil", caption: "Kombin" },
    ],
    services: [
      { t: "Beden", d: "S–XL tablo. Model boyu yazılır." },
      { t: "İade", d: "14 gün. Etiket duracak." },
      { t: "Kapıda ödeme", d: "Hatay içi." },
    ],
    products: [
      { name: "Keten gömlek", price: "₺890", img: P.boutique, tag: "Yeni" },
      { name: "Pantolon", price: "₺1.140", img: P.boutique2 },
      { name: "Elbise", price: "₺1.690", img: P.boutique },
      { name: "Ceket", price: "₺2.240", img: P.boutique2 },
    ],
    choices: ["Gömlek", "Pantolon", "Elbise", "Ceket"],
    reviews: [
      { n: "Hilal S.", t: "Beden tablosu tuttu." },
      { n: "Ece P.", t: "İade sorunsuz oldu." },
    ],
    districts: HATAY,
  },
  {
    slug: "motor-parcasi",
    kind: "shop",
    widget: "shop",
    title: "Motor Parçası",
    brand: "Hatay Oto Parça",
    subtitle: "Yedek parça — marka, şasi, kargo",
    accent: "#111827",
    bg: "#030712",
    hero: P.parts,
    hook: "Şasi no yaz. Yanlış parça gitmesin.",
    lead: "Oto / motor yedek. OEM kodu ve uyumluluk satırda.",
    slides: [
      { src: P.parts, alt: "Atölye", caption: "Parça" },
      { src: P.parts2, alt: "Araç", caption: "Uyum" },
      { src: P.tools2, alt: "Depo", caption: "Stok" },
    ],
    services: [
      { t: "Şasi sorgu", d: "Fotoğraf + model yılı." },
      { t: "OEM kod", d: "Eşdeğer alternatif yazılı." },
      { t: "Kargo", d: "Aynı gün kesiğe kadar." },
    ],
    products: [
      { name: "Fren balata set", price: "₺1.280", img: P.parts, tag: "Stokta" },
      { name: "Yağ filtresi", price: "₺240", img: P.parts2 },
      { name: "Amortisör", price: "₺2.150", img: P.tools },
      { name: "Far (sağ)", price: "Teklif", img: P.parts2 },
    ],
    choices: ["Fren", "Filtre", "Elektrik", "Kaporta"],
    reviews: [
      { n: "Usta Rıza", t: "Şasiden doğru balata geldi." },
      { n: "Emre C.", t: "Far OEM kodu faturada." },
    ],
    districts: HATAY,
  },
  {
    slug: "ozel-yazilim",
    kind: "pro",
    widget: "software",
    title: "Özel Yazılım",
    brand: "Hatay360 Yazılım",
    subtitle: "Sipariş, stok, randevu — size özel panel",
    accent: "#00a8c4",
    bg: "#071b22",
    hero: P.code,
    hook: "Hazır paket yetmeyince özel panel yazılır.",
    lead: "KOBİ yazılımı. Lisanslı BUNG değil; işletmenize göre ekran.",
    slides: [
      { src: P.code, alt: "Kod", caption: "Geliştirme" },
      { src: P.code2, alt: "Panel", caption: "Panel" },
      { src: P.corp2, alt: "Ekip", caption: "Keşif" },
    ],
    services: [
      { t: "Keşif", d: "Süreç çizilir. Abartı yok." },
      { t: "Modül", d: "Sipariş, stok, randevu, rapor." },
      { t: "Teslim", d: "Eğitim + 30 gün düzeltme." },
    ],
    choices: ["Sipariş paneli", "Randevu", "Saha ekibi", "Entegrasyon"],
    reviews: [
      { n: "Atölye sahibi", t: "Excel bitti, panel duruyor." },
      { n: "Depo sorumlu", t: "Stok hareketi görünür oldu." },
    ],
    districts: ["Uzaktan / Hatay"],
  },
  {
    slug: "emlak",
    kind: "pro",
    widget: "listing",
    title: "Emlak Ofisi",
    brand: "Antakya Emlak",
    subtitle: "Satılık / kiralık — ilan, m², oda",
    accent: "#0369a1",
    bg: "#0c4a6e",
    hero: P.house,
    hook: "İlan gerçek fotoğraf. m² ve aidat yazılı.",
    lead: "Emlak vitrini. Portföy, filtre, randevulu gezi.",
    slides: [
      { src: P.house, alt: "Ev", caption: "Satılık" },
      { src: P.house2, alt: "Villa", caption: "Villa" },
      { src: P.house3, alt: "Daire", caption: "Daire" },
    ],
    services: [
      { t: "Satılık", d: "Tapu ve iskan notu." },
      { t: "Kiralık", d: "Depozito ve aidat ayrı." },
      { t: "Gezi", d: "Randevu. Anahtar ofiste." },
    ],
    listings: [
      { name: "Defne 3+1", meta: "145 m² · 3. kat · asansör", price: "₺4.250.000", img: P.house },
      { name: "Antakya 2+1 kiralık", meta: "95 m² · eşyalı", price: "₺18.500 / ay", img: P.house2 },
      { name: "İskenderun villa", meta: "220 m² · bahçe", price: "Teklif", img: P.house3 },
      { name: "Samandağ yazlık", meta: "Denize 800 m", price: "₺6.900.000", img: P.house2 },
    ],
    choices: ["Satılık daire", "Kiralık", "Arsa", "İşyeri"],
    reviews: [
      { n: "Mehmet K.", t: "İlandaki m² yerinde tuttu." },
      { n: "Selin A.", t: "Gezi randevusu saatindeydi." },
    ],
    districts: HATAY,
  },
  {
    slug: "restoran",
    kind: "local",
    widget: "menu",
    title: "Restoran",
    brand: "Asmalı Mutfak",
    subtitle: "Menü, rezervasyon, paket servis",
    accent: "#b45309",
    bg: "#431407",
    hero: P.resto,
    hook: "Rezervasyon saati. Menü güncel, stok biteni çizeriz.",
    lead: "Restoran sitesi. Menü, masa, paket. Abartılı yıldız yok.",
    slides: [
      { src: P.resto, alt: "Salon", caption: "Salon" },
      { src: P.resto2, alt: "Tabak", caption: "Mutfak" },
      { src: P.cake2, alt: "Tatlı", caption: "Tatlı" },
    ],
    services: [
      { t: "Rezervasyon", d: "Kişi sayısı + saat." },
      { t: "Paket", d: "WhatsApp. Teslim aralığı." },
      { t: "Menü", d: "Günlük çorba ayrı." },
    ],
    menu: [
      { cat: "Başlangıç", name: "Humus", price: "₺120" },
      { cat: "Başlangıç", name: "İçli köfte", price: "₺160" },
      { cat: "Ana", name: "Künefe hariç kebap porsiyon", price: "₺420" },
      { cat: "Ana", name: "Izgara karışık", price: "₺580" },
      { cat: "Tatlı", name: "Künefe", price: "₺180" },
      { cat: "İçecek", name: "Ayran / şalgam", price: "₺40" },
    ],
    choices: ["2 kişilik masa", "4 kişilik", "Paket", "Özel gün"],
    reviews: [
      { n: "Hakan Y.", t: "Rezervasyon tutuldu, bekletilmedik." },
      { n: "Lale T.", t: "Paket saatinde, sıcak." },
    ],
    districts: HATAY,
  },
  {
    slug: "aktar",
    kind: "local",
    widget: "shop",
    title: "Aktar & Baharat",
    brand: "Çarşı Aktar",
    subtitle: "Baharat, çay, aktariye — kg",
    accent: "#c2410c",
    bg: "#7c2d12",
    hero: P.spice,
    hook: "Sumak, isot, zahter. Kg ve paket net.",
    lead: "Aktar vitrini. Baharat taze çekim, tarih yazılı.",
    slides: [
      { src: P.spice, alt: "Baharat", caption: "Baharat" },
      { src: P.market, alt: "Çarşı", caption: "Çarşı" },
      { src: P.cake3, alt: "Çay", caption: "Çay / aktar" },
    ],
    services: [
      { t: "Baharat kg", d: "Isot, sumak, karabiber." },
      { t: "Çay", d: "Dökme. Tadım yok, koku var." },
      { t: "Aktariye", d: "Bitki çayı. Tavsiye abartısız." },
    ],
    products: [
      { name: "Hatay isot 250 g", price: "₺95", img: P.spice, tag: "Yerel" },
      { name: "Zahter", price: "₺80", img: P.spice2 },
      { name: "Sumak", price: "₺70", img: P.spice },
      { name: "Karışık baharat set", price: "₺240", img: P.market2 },
    ],
    choices: ["Isot", "Zahter", "Çay", "Set"],
    reviews: [
      { n: "Ayşe T.", t: "Isot taze, paket gramaj tuttu." },
      { n: "Cemil D.", t: "Set hediyelik güzel." },
    ],
    districts: HATAY,
  },
  {
    slug: "telefoncu",
    kind: "local",
    widget: "call",
    title: "Telefoncu",
    brand: "Ekran Tamir",
    subtitle: "Ekran, batarya, ikinci el — süre net",
    accent: "#2563eb",
    bg: "#1e3a8a",
    hero: P.phone,
    hook: "Ekran kaç saatte biter, başta söylenir.",
    lead: "Telefon tamir + ikinci el. Yedek parça orijinal/eşdeğer yazılır.",
    slides: [
      { src: P.phone, alt: "Telefon", caption: "Cihaz" },
      { src: P.phone2, alt: "Tamir", caption: "Tamir" },
      { src: P.pc2, alt: "Tezgah", caption: "Tezgah" },
    ],
    services: [
      { t: "Ekran", d: "Model + süre + fiyat." },
      { t: "Batarya", d: "Şişme kontrol. Garanti süre." },
      { t: "İkinci el", d: "İmei ve kutu notu." },
    ],
    choices: ["Ekran", "Batarya", "Şarj soketi", "İkinci el"],
    reviews: [
      { n: "Onur P.", t: "Ekran 2 saatte. Eşdeğer yazdılar." },
      { n: "Mert A.", t: "İkinci elde iMei gösterdiler." },
    ],
    districts: HATAY,
  },
  {
    slug: "bilgisayarci",
    kind: "local",
    widget: "call",
    title: "Bilgisayarcı",
    brand: "Hatay PC",
    subtitle: "Format, laptop, toplayıcı sistem",
    accent: "#4f46e5",
    bg: "#312e81",
    hero: P.pc,
    hook: "Format + yedek. Laptop ısınma ayrı teşhis.",
    lead: "Bilgisayar tamir ve satış. Parça faturalı.",
    slides: [
      { src: P.pc, alt: "Laptop", caption: "Laptop" },
      { src: P.pc2, alt: "Kart", caption: "Donanım" },
      { src: P.code, alt: "Masabaşı", caption: "Servis" },
    ],
    services: [
      { t: "Format", d: "Yedek alınır. Lisans konuşulur." },
      { t: "Laptop", d: "Ekran, batarya, fan." },
      { t: "Toplama", d: "Liste + fatura." },
    ],
    choices: ["Format", "Fan / pasta", "RAM / SSD", "Toplama liste"],
    reviews: [
      { n: "Berk U.", t: "SSD takıp Windows’u onlar kurdu." },
      { n: "Zeynep H.", t: "Isınma pasta ile düzeldi." },
    ],
    districts: HATAY,
  },
  {
    slug: "kurumsal",
    kind: "pro",
    widget: "call",
    title: "Kurumsal Firma",
    brand: "Hatay Endüstri",
    subtitle: "B2B vitrin — üretim, kalite, teklif",
    accent: "#0f766e",
    bg: "#134e4a",
    hero: P.corp,
    hook: "Fabrikayı anlatan site. Teklif formu, kalite belgeleri.",
    lead: "Kurumsal web. Hakkımızda şişirme değil; kapasite ve referans.",
    slides: [
      { src: P.corp, alt: "Bina", caption: "Tesis" },
      { src: P.corp2, alt: "Ofis", caption: "Ofis" },
      { src: P.code2, alt: "İş", caption: "Üretim" },
    ],
    services: [
      { t: "Üretim", d: "Kapasite ve teslim süresi." },
      { t: "Kalite", d: "Belge PDF. Sahte rozet yok." },
      { t: "Teklif", d: "B2B form. Yetkili mail." },
    ],
    choices: ["Ürün kataloğu", "Teklif", "Ziyaret", "İnsan kaynakları"],
    reviews: [
      { n: "Satın alma", t: "Teklif formu işe yaradı." },
      { n: "İş ortağı", t: "Tesis fotoğrafları gerçekçi." },
    ],
    districts: ["Hatay / ihracat"],
  },
  {
    slug: "avukat",
    kind: "pro",
    widget: "book",
    title: "Hukuk Bürosu",
    brand: "Av. Ofisi",
    subtitle: "Danışma randevusu — aile, icra, ticaret",
    accent: "#1e3a5f",
    bg: "#0f172a",
    hero: P.law,
    hook: "İlk görüşme randevulu. Dosya WhatsApp’tan değil, ofiste.",
    lead: "Avukat sitesi. Uzmanlık alanları net. Sonuç vaadi yok.",
    slides: [
      { src: P.law, alt: "Hukuk", caption: "Bürosu" },
      { src: P.law2, alt: "Görüşme", caption: "Görüşme" },
      { src: P.corp2, alt: "Ofis", caption: "Ofis" },
    ],
    services: [
      { t: "Aile / boşanma", d: "Randevu. Belge listesi." },
      { t: "İcra", d: "Dosya inceleme ücreti başta." },
      { t: "Ticaret", d: "Sözleşme ve şirket." },
    ],
    choices: ["İlk danışma", "İcra", "Aile", "Ticaret"],
    reviews: [
      { n: "Müvekkil A.", t: "Randevu saati tutuldu." },
      { n: "Şirket yetkilisi", t: "Sözleşme taslağı netti." },
    ],
    districts: ["Antakya", "İskenderun"],
  },
  {
    slug: "mobil-uygulama",
    kind: "pro",
    widget: "app",
    title: "Mobil Uygulama",
    brand: "Hatay360 Apps",
    subtitle: "Android & iOS — size özel uygulama",
    accent: "#00a8c4",
    bg: "#071b22",
    hero: P.app,
    hook: "Mağaza ikonu, bildirim, üye girişi. Web sitesi değil; uygulama.",
    lead: "Özel mobil yazılım örneği. Android ve iOS. Store yayın süreci ayrıca.",
    slides: [
      { src: P.app, alt: "Telefon", caption: "iOS / Android" },
      { src: P.app2, alt: "UI", caption: "Arayüz" },
      { src: P.code2, alt: "Geliştirme", caption: "Geliştirme" },
    ],
    services: [
      { t: "Keşif", d: "Ekran listesi. Native / çapraz." },
      { t: "Yayın", d: "Play / App Store hesapları sizde." },
      { t: "Bildirim", d: "Kampanya ve randevu hatırlatma." },
    ],
    choices: ["Sipariş uygulaması", "Randevu", "Saha ekibi", "Üye kulübü"],
    reviews: [
      { n: "Restoran işletmesi", t: "Paket uygulaması sade kaldı." },
      { n: "Klinik", t: "Randevu bildirimi işe yaradı." },
    ],
    districts: ["Uzaktan / Hatay"],
  },
  {
    slug: "eczane",
    kind: "local",
    widget: "call",
    title: "Eczane",
    brand: "Defne Eczanesi",
    subtitle: "Nöbet, stok, WhatsApp sipariş",
    accent: "#059669",
    bg: "#064e3b",
    hero: P.pharm,
    hook: "Nöbetçi bugün bizde. İlacınız yoksa alternatifini yazarız.",
    lead: "Eczane sitesi. Nöbet saati, stok sorusu, kargo. Reçeteyi WhatsApp’tan gönderin.",
    slides: [
      { src: P.pharm, alt: "Eczane", caption: "Tezgah" },
      { src: P.pharm2, alt: "İlaç", caption: "Stok" },
      { src: P.market, alt: "Raflar", caption: "Raflar" },
    ],
    services: [
      { t: "Nöbet", d: "Bugün / yarın takvimi." },
      { t: "WhatsApp", d: "Reçete fotoğrafı." },
      { t: "Teslim", d: "Defne ve Antakya." },
    ],
    choices: ["Nöbetçi mi?", "Stok sor", "Evde teslim", "Cilt bakımı"],
    reviews: [
      { n: "Ayşe D.", t: "Nöbet saati sitede doğruydu." },
      { n: "Kemal T.", t: "Reçeteyi WhatsApp’tan hallettik." },
    ],
    districts: ["Defne", "Antakya"],
  },
  {
    slug: "oto-yikama",
    kind: "local",
    widget: "book",
    title: "Oto yıkama",
    brand: "Antakya Detail",
    subtitle: "Randevu, paket, sıra yok",
    accent: "#0284c7",
    bg: "#0c4a6e",
    hero: P.wash,
    hook: "Sıraya girmeyin. Saat alın, aracı bırakın.",
    lead: "Yıkama + iç detay. Fiyat pakette yazılı. Randevusuz gelen bekler.",
    slides: [
      { src: P.wash, alt: "Yıkama", caption: "Dış yıkama" },
      { src: P.wash2, alt: "Araç", caption: "Teslim" },
      { src: P.parts, alt: "Atölye", caption: "Alan" },
    ],
    services: [
      { t: "Randevu", d: "30 / 60 / 90 dk." },
      { t: "Paket", d: "Dış, iç, seramik." },
      { t: "Filo", d: "Şirket araçları." },
    ],
    choices: ["Dış yıkama", "İç detay", "Seramik", "Filo"],
    reviews: [
      { n: "Okan B.", t: "Saat tutuldu, bekletilmedik." },
      { n: "Filo sorumlusu", t: "Aylık fatura net." },
    ],
    districts: ["Antakya", "İskenderun"],
  },
  {
    slug: "dugun-salonu",
    kind: "local",
    widget: "book",
    title: "Düğün salonu",
    brand: "Asi Vadisi",
    subtitle: "Tarih, menü, keşif",
    accent: "#be185d",
    bg: "#4a044e",
    hero: P.wedding,
    hook: "Tarih dolu mu, menü ne, keşif ne zaman — net yazılır.",
    lead: "Salon sitesi. Takvim, kişi sayısı, menü paketi. Abartılı slayt yok.",
    slides: [
      { src: P.wedding, alt: "Salon", caption: "Salon" },
      { src: P.wedding2, alt: "Masa", caption: "Organizasyon" },
      { src: P.resto2, alt: "İkram", caption: "İkram" },
    ],
    services: [
      { t: "Tarih", d: "Boş günler listesi." },
      { t: "Menü", d: "Kişi başı paket." },
      { t: "Keşif", d: "Hafta içi randevu." },
    ],
    choices: ["Nişan", "Düğün", "Sünnet", "Kurumsal yemek"],
    reviews: [
      { n: "Zeynep & Ali", t: "Sözleşme maddeleri açıktı." },
      { n: "Düğün sahibi", t: "Keşif saatinde başladık." },
    ],
    districts: ["Antakya", "Defne", "Samandağ"],
  },
  {
    slug: "firin",
    kind: "local",
    widget: "menu",
    title: "Fırın",
    brand: "Künefe Fırını",
    subtitle: "Günün ekmeği, sipariş saati",
    accent: "#c2410c",
    bg: "#7c2d12",
    hero: P.bread,
    hook: "Sabah ekmeği 06:30. Künefe siparişi akşamdan yazılır.",
    lead: "Fırın sitesi. Günlük ürün, biten kalem çizilir. Teslim semtleri net.",
    slides: [
      { src: P.bread, alt: "Ekmek", caption: "Fırın" },
      { src: P.bread2, alt: "Somun", caption: "Somun" },
      { src: P.cake3, alt: "Tatlı", caption: "Tatlı" },
    ],
    services: [
      { t: "Günlük", d: "Ekmek / pide saati." },
      { t: "Sipariş", d: "WhatsApp liste." },
      { t: "Teslim", d: "Antakya merkez." },
    ],
    menu: [
      { cat: "Ekmek", name: "Somun", price: "₺18" },
      { cat: "Ekmek", name: "Tırnak pide", price: "₺45" },
      { cat: "Tatlı", name: "Künefe porsiyon", price: "₺160" },
      { cat: "Tatlı", name: "Katmer", price: "₺140" },
    ],
    choices: ["Sabah ekmek", "Pide", "Künefe", "Toplu sipariş"],
    reviews: [
      { n: "Komşu", t: "Biten ürün sitede çiziliydi." },
      { n: "Lokanta", t: "Toplu pide saatinde geldi." },
    ],
    districts: ["Antakya", "Defne"],
  },
  {
    slug: "cicekci",
    kind: "shop",
    widget: "shop",
    title: "Çiçekçi",
    brand: "Asi Çiçek",
    subtitle: "Buket, teslim saati, kart",
    accent: "#db2777",
    bg: "#831843",
    hero: P.flower,
    hook: "Aynı gün teslim. Kart notunu siz yazın.",
    lead: "Çiçekçi vitrini. Stoktaki buket, teslim aralığı. Sürpriz adres kapalı bırakılmaz.",
    slides: [
      { src: P.flower, alt: "Çiçek", caption: "Vitrin" },
      { src: P.flower2, alt: "Buket", caption: "Buket" },
      { src: P.wedding2, alt: "Organizasyon", caption: "Özel gün" },
    ],
    services: [
      { t: "Teslim", d: "Antakya / Defne." },
      { t: "Kart", d: "Not sizden." },
      { t: "Düğün", d: "Salon süs ayrı." },
    ],
    products: [
      { name: "Gül buketi", price: "₺850", img: P.flower, tag: "Aynı gün" },
      { name: "Mevsim karışık", price: "₺620", img: P.flower2 },
      { name: "Saksı orkide", price: "₺1.150", img: P.wedding },
      { name: "Cenaze çelengi", price: "₺1.400", img: P.flower2 },
    ],
    choices: ["Aynı gün", "Doğum günü", "Düğün", "Cenaze"],
    reviews: [
      { n: "Elif S.", t: "Saat 16 teslim tutuldu." },
      { n: "Damat", t: "Gelin buketi sözleşmedeki gibi." },
    ],
    districts: HATAY,
  },
  {
    slug: "dis-klinigi",
    kind: "local",
    widget: "book",
    title: "Diş kliniği",
    brand: "Antakya Diş",
    subtitle: "Randevu, tedavi planı, röntgen notu",
    accent: "#0f766e",
    bg: "#134e4a",
    hero: P.dental,
    hook: "Randevu saati net. Tedavi basamağı yazılır, sürpriz fatura yok.",
    lead: "Klinik sitesi. İlk muayene, dolgu, implant keşif. Röntgen WhatsApp’tan.",
    slides: [
      { src: P.dental, alt: "Klinik", caption: "Klinik" },
      { src: P.dental2, alt: "Ünit", caption: "Ünit" },
      { src: P.pharm2, alt: "Steril", caption: "Steril" },
    ],
    services: [
      { t: "Randevu", d: "İlk muayene 20 dk." },
      { t: "Plan", d: "Yazılı tedavi basamağı." },
      { t: "Acil", d: "Ağrı için boşluk varsa." },
    ],
    choices: ["İlk muayene", "Dolgu", "Kanal", "İmplant keşif"],
    reviews: [
      { n: "Merve A.", t: "Saat tutuldu, bekletilmedik." },
      { n: "Hasta yakını", t: "Fiyat basamağı kâğıtta durdu." },
    ],
    districts: ["Antakya", "Defne", "İskenderun"],
  },
  {
    slug: "optik",
    kind: "shop",
    widget: "shop",
    title: "Optik",
    brand: "İskenderun Optik",
    subtitle: "Çerçeve, cam, numara kaydı",
    accent: "#1d4ed8",
    bg: "#1e3a8a",
    hero: P.glasses,
    hook: "Numaranızı kaydederiz. Çerçeve stokta yoksa sipariş süresi yazılır.",
    lead: "Optik vitrini. Cam tipi, kargo, deneme. Abartılı indirim yok.",
    slides: [
      { src: P.glasses, alt: "Gözlük", caption: "Çerçeve" },
      { src: P.glasses2, alt: "Cam", caption: "Cam" },
      { src: P.phone, alt: "Ölçüm", caption: "Ölçüm" },
    ],
    services: [
      { t: "Ölçüm", d: "Randevu ile." },
      { t: "Cam", d: "Anti-yansı / mavi filtre." },
      { t: "Teslim", d: "Hazır olunca SMS." },
    ],
    products: [
      { name: "Metal çerçeve", price: "₺2.450", img: P.glasses, tag: "Stokta" },
      { name: "Asetat çerçeve", price: "₺1.890", img: P.glasses2 },
      { name: "Güneş camı", price: "₺1.250", img: P.glasses },
      { name: "Lens deneme", price: "₺350", img: P.glasses2 },
    ],
    choices: ["Çerçeve", "Sadece cam", "Güneş", "Lens"],
    reviews: [
      { n: "Burak Y.", t: "Cam süresi 4 gün dedi, 4 günde geldi." },
      { n: "Öğretmen", t: "Numara kaydı sonraki ziyarette hazırdı." },
    ],
    districts: ["İskenderun", "Dörtyol", "Antakya"],
  },
  {
    slug: "kahve",
    kind: "local",
    widget: "menu",
    title: "Kahve dükkanı",
    brand: "Asi Kahve",
    subtitle: "Menü, masa, paket",
    accent: "#92400e",
    bg: "#451a03",
    hero: P.coffee,
    hook: "Menü güncel. Paket 15 dk. Wi-Fi şifresi fişte.",
    lead: "Kafe sitesi. Kahve, tatlı, çalışma masası. Stok biteni çizeriz.",
    slides: [
      { src: P.coffee, alt: "Kahve", caption: "Bar" },
      { src: P.coffee2, alt: "İç mekan", caption: "Salon" },
      { src: P.cake2, alt: "Tatlı", caption: "Tatlı" },
    ],
    services: [
      { t: "Paket", d: "WhatsApp, 15 dk." },
      { t: "Masa", d: "2–4 kişilik." },
      { t: "Etkinlik", d: "Küçük kapanış ayrı." },
    ],
    menu: [
      { cat: "Kahve", name: "Filtre", price: "₺90" },
      { cat: "Kahve", name: "Espresso", price: "₺80" },
      { cat: "Kahve", name: "Türk kahvesi", price: "₺70" },
      { cat: "Tatlı", name: "Cheesecake dilim", price: "₺160" },
    ],
    choices: ["Paket", "2 kişilik masa", "Toplantı köşesi", "Doğum günü pasta"],
    reviews: [
      { n: "Elif K.", t: "Paket 12 dakikada çıktı." },
      { n: "Freelance", t: "Priz ve masa saati yazıyordu." },
    ],
    districts: ["Antakya", "Defne"],
  },
  {
    slug: "lastikci",
    kind: "local",
    widget: "call",
    title: "Lastikçi",
    brand: "İskenderun Lastik",
    subtitle: "Mevsim lastiği, balans, yol yardım",
    accent: "#b45309",
    bg: "#431407",
    hero: P.tire,
    hook: "Ebatı yazın, stok var mı hemen döneriz. Yol yardım numarası sitede durur.",
    lead: "Lastikçi sitesi. Yaz/kış stok, balans, depolama. Fiyat ebatla değişir, net yazılır.",
    slides: [
      { src: P.tire, alt: "Lastik", caption: "Atölye" },
      { src: P.tire2, alt: "Jant", caption: "Jant" },
      { src: P.parts, alt: "Servis", caption: "Servis" },
    ],
    services: [
      { t: "Stok", d: "Ebat WhatsApp." },
      { t: "Balans", d: "Aynı gün." },
      { t: "Yol yardım", d: "İskenderun çevre yol." },
    ],
    choices: ["Yaz lastiği", "Kış lastiği", "Balans", "Depolama"],
    reviews: [
      { n: "Şoför", t: "205/55/16 stokta vardı, 40 dk." },
      { n: "Filo", t: "Fatura ebat satırında durdu." },
    ],
    districts: ["İskenderun", "Dörtyol", "Payas"],
  },
  {
    slug: "pet-shop",
    kind: "shop",
    widget: "shop",
    title: "Pet shop",
    brand: "Defne Pati",
    subtitle: "Mama, tasma, randevusuz tıraş yok",
    accent: "#c026d3",
    bg: "#701a75",
    hero: P.pet,
    hook: "Mama stoğu sitede. Tıraş için saat alın; kapıda sıra yok.",
    lead: "Pet shop vitrini. Mama kilo, tasma, veteriner yönlendirme ayrı.",
    slides: [
      { src: P.pet, alt: "Köpek", caption: "Dükkan" },
      { src: P.pet2, alt: "Bakım", caption: "Bakım" },
      { src: P.vet3, alt: "Mama", caption: "Mama" },
    ],
    services: [
      { t: "Mama", d: "Kilo ve marka." },
      { t: "Tıraş", d: "Randevu." },
      { t: "Veteriner", d: "Acil yönlendirme." },
    ],
    products: [
      { name: "Yavru mama 3 kg", price: "₺620", img: P.pet, tag: "Stokta" },
      { name: "Yetişkin mama 15 kg", price: "₺1.890", img: P.pet2 },
      { name: "Tasma set", price: "₺240", img: P.pet },
      { name: "Tıraş seansı", price: "₺450", img: P.vet2 },
    ],
    choices: ["Mama", "Tıraş randevu", "Tasma", "Acil yönlendir"],
    reviews: [
      { n: "Pati sahibi", t: "3 kg mama sitedeki fiyatla aynı." },
      { n: "Defne", t: "Tıraş saati tutuldu." },
    ],
    districts: ["Defne", "Antakya"],
  },
  {
    slug: "fotografci",
    kind: "local",
    widget: "book",
    title: "Fotoğrafçı",
    brand: "Antakya Kare",
    subtitle: "Düğün, nişan, ürün çekimi",
    accent: "#57534e",
    bg: "#1c1917",
    hero: P.photo,
    hook: "Tarih dolu mu, teslim kaç gün, ham foto var mı — yazılır.",
    lead: "Fotoğrafçı sitesi. Paket, ön ödeme, teslim süresi. Slayt abartısı yok.",
    slides: [
      { src: P.photo, alt: "Stüdyo", caption: "Stüdyo" },
      { src: P.photo2, alt: "Çekim", caption: "Çekim" },
      { src: P.wedding, alt: "Düğün", caption: "Düğün" },
    ],
    services: [
      { t: "Düğün", d: "Saat + albüm." },
      { t: "Ürün", d: "Katalog 12 kare." },
      { t: "Teslim", d: "Gün sayısı sözleşmede." },
    ],
    choices: ["Nişan", "Düğün", "Ürün çekimi", "Pasaport"],
    reviews: [
      { n: "Gelin", t: "Teslim 10 gün dedi, 9. günde geldi." },
      { n: "Butik", t: "Ürün kareleri sitedeki örnek gibiydi." },
    ],
    districts: ["Antakya", "Defne", "İskenderun"],
  },
  {
    slug: "muhasebeci",
    kind: "pro",
    widget: "book",
    title: "Muhasebe ofisi",
    brand: "Hatay Defter",
    subtitle: "e-Fatura, bordro, randevu",
    accent: "#0f766e",
    bg: "#042f2e",
    hero: P.desk,
    hook: "Evrak listesi sitede. Randevusuz gelen bekler.",
    lead: "Mali müşavir vitrini. e-Fatura, SGK, şirket kuruluş. Gizlilik notu net.",
    slides: [
      { src: P.desk, alt: "Ofis", caption: "Ofis" },
      { src: P.desk2, alt: "Evrak", caption: "Evrak" },
      { src: P.corp2, alt: "Toplantı", caption: "Görüşme" },
    ],
    services: [
      { t: "e-Fatura", d: "Kurulum + ay." },
      { t: "Bordro", d: "Personel sayısı." },
      { t: "Kuruluş", d: "Şirket evrak listesi." },
    ],
    choices: ["e-Fatura", "Bordro", "Şirket kuruluş", "KDV iade"],
    reviews: [
      { n: "Şirket yetkilisi", t: "Evrak listesi sitede duruyordu." },
      { n: "Esnaf", t: "Randevu saati tutuldu." },
    ],
    districts: ["Antakya", "İskenderun"],
  },
  {
    slug: "dershane",
    kind: "local",
    widget: "book",
    title: "Dershane / kurs",
    brand: "Antakya Kurs",
    subtitle: "Sınıf, kayıt, deneme",
    accent: "#1d4ed8",
    bg: "#1e3a8a",
    hero: P.class,
    hook: "Kontenjan dolu mu, deneme tarihi ne — sitede yazılır.",
    lead: "Kurs sitesi. Sınıf kontenjanı, kayıt belgesi, veli görüşmesi. Abartılı başarı yüzdesi yok.",
    slides: [
      { src: P.class, alt: "Sınıf", caption: "Sınıf" },
      { src: P.class2, alt: "Çalışma", caption: "Çalışma" },
      { src: P.desk, alt: "Kayıt", caption: "Kayıt" },
    ],
    services: [
      { t: "Kayıt", d: "Belge listesi." },
      { t: "Deneme", d: "Tarih takvimi." },
      { t: "Veli", d: "Görüşme randevusu." },
    ],
    choices: ["LGS", "YKS", "İngilizce", "Deneme sınavı"],
    reviews: [
      { n: "Veli", t: "Kontenjan sitede günceldi." },
      { n: "Öğrenci", t: "Deneme tarihi tutuldu." },
    ],
    districts: ["Antakya", "Defne", "İskenderun"],
  },
  {
    slug: "oto-elektrik",
    kind: "local",
    widget: "call",
    title: "Oto elektrik",
    brand: "İskenderun Oto Elektrik",
    subtitle: "Arıza, akü, far ayarı",
    accent: "#ea580c",
    bg: "#7c2d12",
    hero: P.parts,
    hook: "Arıza tarifini yazın. Akü stok varsa aynı gün.",
    lead: "Oto elektrik sitesi. Akü, far, klima elektrik. Yol yardım numarası net.",
    slides: [
      { src: P.parts, alt: "Atölye", caption: "Atölye" },
      { src: P.parts2, alt: "Araç", caption: "Araç" },
      { src: P.tire2, alt: "Servis", caption: "Servis" },
    ],
    services: [
      { t: "Akü", d: "Stok / sipariş." },
      { t: "Far", d: "Ayar ve değişim." },
      { t: "Arıza", d: "WhatsApp ses." },
    ],
    choices: ["Akü", "Far ayarı", "Klima elektrik", "Yol yardım"],
    reviews: [
      { n: "Taksi", t: "Akü aynı gündü." },
      { n: "Nakliyat", t: "Far ayarı 40 dk." },
    ],
    districts: ["İskenderun", "Dörtyol", "Payas"],
  },
  {
    slug: "klima",
    kind: "local",
    widget: "book",
    title: "Klima servisi",
    brand: "Antakya Klima",
    subtitle: "Montaj, gaz, bakım randevusu",
    accent: "#0284c7",
    bg: "#0c4a6e",
    hero: P.ac,
    hook: "Yaz gelmeden bakım alın. Gaz kaçıyorsa aynı gün bakılır.",
    lead: "Klima sitesi. Montaj, gaz doldurma, bakım. Semt ve randevu saati net yazılır.",
    slides: [
      { src: P.ac, alt: "Klima", caption: "İç ünite" },
      { src: P.ac2, alt: "Servis", caption: "Servis" },
      { src: P.house, alt: "Ev", caption: "Montaj" },
    ],
    services: [
      { t: "Montaj", d: "Duvar / kaset." },
      { t: "Gaz", d: "Kaçak ve dolum." },
      { t: "Bakım", d: "Sezon öncesi." },
    ],
    choices: ["Montaj", "Gaz dolum", "Bakım", "Arıza"],
    reviews: [
      { n: "Defne ev", t: "Randevu saatinde geldiler." },
      { n: "Dükkân", t: "Gaz kaçağı aynı gündü." },
    ],
    districts: ["Antakya", "Defne", "Samandağ"],
  },
  {
    slug: "tesisatci",
    kind: "local",
    widget: "call",
    title: "Tesisatçı",
    brand: "Defne Tesisat",
    subtitle: "Su, kaçak, tıkanıklık",
    accent: "#0f766e",
    bg: "#134e4a",
    hero: P.pipe,
    hook: "Tıkanıklık ve kaçak için fotoğraf atın. Gelmeden fiyat aralığı söylenir.",
    lead: "Tesisat sitesi. Acil kaçak, tıkanıklık, kombi bağlantı. WhatsApp fotoğrafı yeter.",
    slides: [
      { src: P.pipe, alt: "Tesisat", caption: "Boru" },
      { src: P.pipe2, alt: "Alet", caption: "Müdahale" },
      { src: P.nalbur2, alt: "Malzeme", caption: "Malzeme" },
    ],
    services: [
      { t: "Kaçak", d: "Su / tesisat." },
      { t: "Tıkanıklık", d: "Lavabo / pimaş." },
      { t: "Kombi", d: "Bağlantı / petek." },
    ],
    choices: ["Su kaçağı", "Tıkanıklık", "Kombi", "Yeni hat"],
    reviews: [
      { n: "Antakya daire", t: "Fotoğraftan fiyat aralığı netti." },
      { n: "Site yönetimi", t: "Aynı gün tıkanıklık açıldı." },
    ],
    districts: ["Defne", "Antakya", "Kırıkhan"],
  },
  {
    slug: "otel",
    kind: "local",
    widget: "book",
    title: "Otel / pansiyon",
    brand: "Arsuz Sahil",
    subtitle: "Oda, tarih, kahvaltı",
    accent: "#0369a1",
    bg: "#0c4a6e",
    hero: P.hotel,
    hook: "Tarih yazın, oda tipi seçin. Kapora ve iptal kuralı sitede durur.",
    lead: "Sahil oteli sitesi. Müsaitlik, kahvaltı, deniz mesafesi. WhatsApp rezervasyon; sahte doluluk yok.",
    slides: [
      { src: P.hotel, alt: "Otel", caption: "Oda" },
      { src: P.hotel2, alt: "Lobi", caption: "Lobi" },
      { src: P.resto2, alt: "Kahvaltı", caption: "Kahvaltı" },
    ],
    services: [
      { t: "Oda", d: "Deniz / bahçe." },
      { t: "Tarih", d: "Giriş / çıkış." },
      { t: "Kahvaltı", d: "Dahil / hariç." },
    ],
    choices: ["Standart", "Deniz manzara", "Aile", "Uzun konaklama"],
    reviews: [
      { n: "Aile, Ankara", t: "Kapora ve iptal yazılıydı." },
      { n: "Çift", t: "WhatsApp’tan oda fotoğrafı geldi." },
    ],
    districts: ["Arsuz", "İskenderun", "Samandağ"],
  },
  {
    slug: "zeytinyagi",
    kind: "shop",
    widget: "shop",
    title: "Zeytinyağı",
    brand: "Samandağ Zeytin",
    subtitle: "Hasat yılı, litre, kargo",
    accent: "#65a30d",
    bg: "#365314",
    hero: P.olive,
    hook: "Hasat yılı şişede yazılı. Litre fiyatı net; kargo Antakya içi ayrı.",
    lead: "Zeytinyağı vitrini. Filtre, asit, teneke / cam. Toplu sipariş WhatsApp’tan.",
    slides: [
      { src: P.olive, alt: "Zeytin", caption: "Hasat" },
      { src: P.olive2, alt: "Yağ", caption: "Şişe" },
      { src: P.spice, alt: "Aktar", caption: "Dükkân" },
    ],
    services: [
      { t: "Hasat", d: "Yıl şişede." },
      { t: "Litre", d: "Cam / teneke." },
      { t: "Kargo", d: "Hatay içi / dışı." },
    ],
    products: [
      { name: "Naturel sızma 1 L", price: "₺420", img: P.olive, tag: "Cam" },
      { name: "Naturel sızma 5 L", price: "₺1.850", img: P.olive2, tag: "Teneke" },
      { name: "Erken hasat 500 ml", price: "₺280", img: P.spice },
      { name: "Zeytin kahvaltılık", price: "₺190", img: P.spice2 },
    ],
    choices: ["1 litre", "5 litre", "Erken hasat", "Toplu koli"],
    reviews: [
      { n: "Defne ev", t: "Hasat yılı etikette vardı." },
      { n: "Lokanta", t: "5 L teneke kargo netti." },
    ],
    districts: ["Samandağ", "Altınözü", "Yayladağı"],
  },
  {
    slug: "elektrikci",
    kind: "local",
    widget: "call",
    title: "Elektrikçi",
    brand: "Antakya Elektrik",
    subtitle: "Arıza, pano, keşif",
    accent: "#ca8a04",
    bg: "#713f12",
    hero: P.nalbur,
    hook: "Sigorta atıyorsa fotoğraf atın. Keşif ücreti sitede yazılı.",
    lead: "Elektrikçi sitesi. Ev / işyeri arıza, pano, aydınlatma. Keşif ve işçilik ayrı satır.",
    slides: [
      { src: P.nalbur, alt: "Pano", caption: "Pano" },
      { src: P.nalbur2, alt: "Kablo", caption: "Hat" },
      { src: P.house, alt: "Ev", caption: "Keşif" },
    ],
    services: [
      { t: "Arıza", d: "Sigorta / priz." },
      { t: "Pano", d: "Yenileme." },
      { t: "Keşif", d: "Ücret sitede." },
    ],
    choices: ["Ev arıza", "İşyeri pano", "Aydınlatma", "Topraklama"],
    reviews: [
      { n: "Defne daire", t: "Keşif ücreti sürpriz olmadı." },
      { n: "Dükkân", t: "Pano aynı gün bitti." },
    ],
    districts: ["Antakya", "Defne", "Kırıkhan"],
  },
  {
    slug: "kres",
    kind: "local",
    widget: "book",
    title: "Kreş",
    brand: "Defne Minik Adım",
    subtitle: "Kontenjan, servis, yemek",
    accent: "#db2777",
    bg: "#9d174d",
    hero: P.class,
    hook: "Kontenjan dolu mu, servis hangi mahalle, yemek listesi — sitede durur.",
    lead: "Kreş sitesi. Yaş grubu, ücret aralığı, servis hattı. WhatsApp kayıt; sahte kontenjan yok.",
    slides: [
      { src: P.class, alt: "Sınıf", caption: "Sınıf" },
      { src: P.class2, alt: "Bahçe", caption: "Bahçe" },
      { src: P.cake, alt: "Yemek", caption: "Öğün" },
    ],
    services: [
      { t: "Kontenjan", d: "Yaş grubu." },
      { t: "Servis", d: "Mahalle listesi." },
      { t: "Kayıt", d: "WhatsApp form." },
    ],
    choices: ["0–2 yaş", "3–4 yaş", "5–6 yaş", "Yaz okulu"],
    reviews: [
      { n: "Anne, Defne", t: "Servis mahalleleri sitede yazılıydı." },
      { n: "Baba, Antakya", t: "Kontenjan telefonla doğrulandı." },
    ],
    districts: ["Defne", "Antakya", "Samandağ"],
  },
  {
    slug: "camci",
    kind: "local",
    widget: "call",
    title: "Camcı",
    brand: "Antakya Cam",
    subtitle: "Pencere, duşakabin, keşif",
    accent: "#0284c7",
    bg: "#0c4a6e",
    hero: P.house,
    hook: "Kırık cam fotoğrafı yeter. Ölçüye gelmeden fiyat aralığı söylenir.",
    lead: "Camcı sitesi. Pencere, balkon, duşakabin. Keşif ücreti sitede; aynı gün acil ayrı yazılır.",
    slides: [
      { src: P.house, alt: "Pencere", caption: "Pencere" },
      { src: P.house2, alt: "Cephe", caption: "Cephe" },
      { src: P.nalbur2, alt: "Atölye", caption: "Atölye" },
    ],
    services: [
      { t: "Pencere", d: "Çift cam / sineklik." },
      { t: "Duşakabin", d: "Ölçü + montaj." },
      { t: "Acil", d: "Kırık cam." },
    ],
    choices: ["Pencere", "Duşakabin", "Tabela camı", "Acil kırık"],
    reviews: [
      { n: "Defne ev", t: "Fotoğraftan ölçü aralığı netti." },
      { n: "Dükkân", t: "Vitrin camı aynı gün." },
    ],
    districts: ["Antakya", "Defne", "Kırıkhan"],
  },
  {
    slug: "insaat",
    kind: "local",
    widget: "call",
    title: "İnşaat / müteahhit",
    brand: "Antakya Yapı",
    subtitle: "Keşif, kaba, tadilat",
    accent: "#b45309",
    bg: "#78350f",
    hero: P.house3,
    hook: "Keşif ücreti sitede. Kaba inşaat ve tadilat ayrı teklif; sürpriz satır yok.",
    lead: "Müteahhit sitesi. Tadilat, kaba, çatı. Fotoğraflı keşif; iş bitince teslim tutanağı.",
    slides: [
      { src: P.house3, alt: "Şantiye", caption: "Şantiye" },
      { src: P.house, alt: "Konut", caption: "Konut" },
      { src: P.house2, alt: "Tadilat", caption: "Tadilat" },
    ],
    services: [
      { t: "Keşif", d: "Ücret yazılı." },
      { t: "Tadilat", d: "Daire / dükkân." },
      { t: "Kaba", d: "Aşamalı ödeme." },
    ],
    choices: ["Tadilat", "Kaba inşaat", "Çatı", "Dış cephe"],
    reviews: [
      { n: "Defne daire", t: "Keşif ve işçilik ayrı satırdı." },
      { n: "Dükkân", t: "Teslim tarihi tutuldu." },
    ],
    districts: ["Antakya", "Defne", "Kırıkhan"],
  },
  {
    slug: "marangoz",
    kind: "local",
    widget: "call",
    title: "Marangoz / mutfak",
    brand: "Defne Ahşap",
    subtitle: "Mutfak, dolap, keşif",
    accent: "#92400e",
    bg: "#451a03",
    hero: P.nalbur,
    hook: "Mutfak dolabı ölçüye. Keşif ücreti sitede; malzeme ayrı satır.",
    lead: "Marangoz sitesi. Mutfak, vestiyer, kapı. Fotoğraflı keşif; teslim tarihi yazılı.",
    slides: [
      { src: P.nalbur, alt: "Atölye", caption: "Atölye" },
      { src: P.house, alt: "Mutfak", caption: "Mutfak" },
      { src: P.tools, alt: "Kesim", caption: "Kesim" },
    ],
    services: [
      { t: "Mutfak", d: "Ölçü + montaj." },
      { t: "Dolap", d: "Yatak odası / vestiyer." },
      { t: "Kapı", d: "İç kapı değişimi." },
    ],
    choices: ["Mutfak dolabı", "Yatak odası", "Kapı", "Tamir"],
    reviews: [
      { n: "Antakya daire", t: "Malzeme ve işçilik ayrı yazıldı." },
      { n: "Defne mutfak", t: "Montaj günü tutuldu." },
    ],
    districts: ["Antakya", "Defne", "Kırıkhan"],
  },
  {
    slug: "kombi",
    kind: "local",
    widget: "call",
    title: "Kombi / beyaz eşya",
    brand: "Antakya Kombi",
    subtitle: "Arıza, bakım, aynı gün",
    accent: "#c2410c",
    bg: "#7c2d12",
    hero: P.ac2,
    hook: "Kombi yanmıyor diye beklemeyin. Petek havası ve kart arızası ayrı yazılır.",
    lead: "Kombi ve beyaz eşya servisi. Klima montajından ayrı: petek, kart, çamaşır makinesi. Keşif ücreti sitede.",
    slides: [
      { src: P.ac2, alt: "Servis", caption: "Servis" },
      { src: P.pipe, alt: "Petek", caption: "Petek" },
      { src: P.house, alt: "Ev", caption: "Ev servisi" },
    ],
    services: [
      { t: "Kombi", d: "Kart / ateşleme." },
      { t: "Petek", d: "Hava alma / yıkama." },
      { t: "Beyaz eşya", d: "Çamaşır / buzdolabı." },
    ],
    choices: ["Kombi yanmıyor", "Petek ısınmıyor", "Çamaşır makinesi", "Buzdolabı"],
    reviews: [
      { n: "Defne daire", t: "Aynı gün kart bakıldı." },
      { n: "Antakya", t: "Petek yıkama ücreti başta söylendi." },
    ],
    districts: ["Antakya", "Defne", "Kırıkhan"],
  },
  {
    slug: "kaporta",
    kind: "local",
    widget: "call",
    title: "Kaporta / oto boya",
    brand: "İskenderun Kaporta",
    subtitle: "Göçük, boya, ekspertiz fotoğrafı",
    accent: "#b91c1c",
    bg: "#7f1d1d",
    hero: P.parts,
    hook: "Çizik fotoğrafı yeter. Boya ve kaporta ayrı satır; sürpriz yok.",
    lead: "Kaporta sitesi. Oto elektrikten ayrı: göçük, boya, tampon. Ekspertiz fotoğrafı sitede.",
    slides: [
      { src: P.parts, alt: "Atölye", caption: "Atölye" },
      { src: P.parts2, alt: "Araç", caption: "Araç" },
      { src: P.wash2, alt: "Boya", caption: "Boya" },
    ],
    services: [
      { t: "Göçük", d: "Kapı / tampon." },
      { t: "Boya", d: "Parça veya komple." },
      { t: "Ekspertiz", d: "Fotoğraflı teklif." },
    ],
    choices: ["Kapı göçüğü", "Tampon", "Komple boya", "Çizik"],
    reviews: [
      { n: "Taksi", t: "Tampon aynı gün." },
      { n: "Özel araç", t: "Boya kodu tuttu." },
    ],
    districts: ["İskenderun", "Dörtyol", "Antakya"],
  },
  {
    slug: "kasap",
    kind: "local",
    widget: "call",
    title: "Mahalle kasabı",
    brand: "Antakya Kasap",
    subtitle: "Kıyma, kuşbaşı, kg fiyatı",
    accent: "#9f1239",
    bg: "#4c0519",
    hero: P.meat,
    hook: "Kıyma oranı sitede. Marketten ayrı: günlük kesim, kg yazılı.",
    lead: "Kasap sitesi. Kıyma, kuşbaşı, kuzu. Fiyat kg; sipariş WhatsApp. Market listesi değil.",
    slides: [
      { src: P.meat, alt: "Tezgah", caption: "Tezgah" },
      { src: P.meat2, alt: "Kesim", caption: "Kesim" },
      { src: P.market, alt: "Vitrin", caption: "Vitrin" },
    ],
    services: [
      { t: "Kıyma", d: "Yağ oranı yazılı." },
      { t: "Kuşbaşı", d: "Kg. Teslim saati." },
      { t: "Kurban / bayram", d: "Ön sipariş." },
    ],
    choices: ["Kıyma", "Kuşbaşı", "Kuzu", "Tavuk"],
    reviews: [
      { n: "Defne", t: "Yağ oranı söyledikleri gibiydi." },
      { n: "Antakya", t: "Bayram ön sipariş tutuldu." },
    ],
    districts: ["Antakya", "Defne", "Kırıkhan"],
  },
  {
    slug: "spor-salonu",
    kind: "local",
    widget: "book",
    title: "Spor salonu",
    brand: "Defne Fitness",
    subtitle: "Üyelik, deneme dersi, saat",
    accent: "#16a34a",
    bg: "#14532d",
    hero: P.gym,
    hook: "Deneme dersi ücretsiz. Kontenjan saati sitede; kapıda pazarlık yok.",
    lead: "Spor salonu sitesi. Üyelik, PT, kadın saati. Fiyat ve doluluk yazılı.",
    slides: [
      { src: P.gym, alt: "Salon", caption: "Salon" },
      { src: P.gym2, alt: "Ağırlık", caption: "Ağırlık" },
      { src: P.class2, alt: "Grup", caption: "Grup ders" },
    ],
    services: [
      { t: "Deneme", d: "1 ders. Randevu." },
      { t: "Üyelik", d: "Aylık / 3 aylık." },
      { t: "PT", d: "Saat ücreti yazılı." },
    ],
    choices: ["Deneme dersi", "Aylık üyelik", "PT", "Kadın saati"],
    reviews: [
      { n: "Defne", t: "Deneme saati kilitlendi." },
      { n: "Antakya", t: "Kadın saati sitede netti." },
    ],
    districts: ["Defne", "Antakya", "İskenderun"],
  },
  {
    slug: "manav",
    kind: "local",
    widget: "call",
    title: "Mahalle manavı",
    brand: "Antakya Manav",
    subtitle: "Meyve, sebze, kg fiyatı",
    accent: "#15803d",
    bg: "#14532d",
    hero: P.produce,
    hook: "Domates kg sitede. Marketten ayrı: günlük tezgah, liste WhatsApp.",
    lead: "Manav sitesi. Meyve sebze kg. Sabah tezgah fotoğrafı; sipariş kapıya.",
    slides: [
      { src: P.produce, alt: "Tezgah", caption: "Tezgah" },
      { src: P.spice, alt: "Sebze", caption: "Sebze" },
      { src: P.market2, alt: "Kasa", caption: "Kasa" },
    ],
    services: [
      { t: "Kg fiyat", d: "Sabah güncellenir." },
      { t: "Kapıya", d: "Mahalle teslim." },
      { t: "Kasa", d: "Karışık sandık." },
    ],
    choices: ["Domates kg", "Karışık kasa", "Yeşillik", "Mevsim meyve"],
    reviews: [
      { n: "Defne", t: "Kg fiyat sitedeki gibiydi." },
      { n: "Antakya", t: "Sabah liste attım, geldi." },
    ],
    districts: ["Antakya", "Defne", "Samandağ"],
  },
  {
    slug: "sigorta",
    kind: "pro",
    widget: "call",
    title: "Sigorta acentesi",
    brand: "Antakya Sigorta",
    subtitle: "DASK, kasko, teklif",
    accent: "#1d4ed8",
    bg: "#1e3a8a",
    hero: P.desk,
    hook: "DASK ve kasko teklifi siteden. Poliçe numarası yazılı; kapıda satış yok.",
    lead: "Sigorta acentesi sitesi. DASK, kasko, sağlık. Teklif satırları ayrı; sürpriz prim yok.",
    slides: [
      { src: P.desk, alt: "Ofis", caption: "Ofis" },
      { src: P.desk2, alt: "Teklif", caption: "Teklif" },
      { src: P.corp2, alt: "Görüşme", caption: "Görüşme" },
    ],
    services: [
      { t: "DASK", d: "Konut. Ada/parsel." },
      { t: "Kasko", d: "Plaka ile teklif." },
      { t: "Sağlık", d: "Aile paketi." },
    ],
    choices: ["DASK", "Kasko", "Trafik", "Sağlık"],
    reviews: [
      { n: "Defne konut", t: "DASK satırları netti." },
      { n: "Antakya araç", t: "Kasko teklifi aynı gün." },
    ],
    districts: ["Antakya", "Defne", "İskenderun"],
  },
  {
    slug: "dugun-organizasyon",
    kind: "local",
    widget: "book",
    title: "Düğün organizasyon",
    brand: "Antakya Organizasyon",
    subtitle: "Host, DJ, çiçek — salon değil",
    accent: "#a21caf",
    bg: "#701a75",
    hero: P.wedding2,
    hook: "Salon ayrı, ekip ayrı. Host, DJ ve çiçek kalemi sitede yazılı.",
    lead: "Organizasyon sitesi. Düğün salonundan ayrı: ekip, zaman çizelgesi, keşif. Mekân kirası bu demoda yok.",
    slides: [
      { src: P.wedding2, alt: "Masa", caption: "Kurulum" },
      { src: P.flower, alt: "Çiçek", caption: "Çiçek" },
      { src: P.photo, alt: "An", caption: "An" },
    ],
    services: [
      { t: "Host", d: "Giriş ve akış." },
      { t: "DJ / ses", d: "Saatlik." },
      { t: "Çiçek", d: "Masa ve gelin." },
    ],
    choices: ["Nişan ekibi", "Düğün ekibi", "Sünnet", "Sadece DJ"],
    reviews: [
      { n: "Zeynep", t: "Salon başka yerdi, ekip netti." },
      { n: "Ali", t: "Zaman çizelgesi tutuldu." },
    ],
    districts: ["Antakya", "Defne", "İskenderun"],
  },
  {
    slug: "zuccaciye",
    kind: "shop",
    widget: "shop",
    title: "Züccaciye",
    brand: "Antakya Züccaciye",
    subtitle: "Porselen, cam, tencere — stok yazılı",
    accent: "#0e7490",
    bg: "#164e63",
    hero: P.dish,
    hook: "Çeyiz listesi sitede. Porselen takım stokta; kargo Hatay içi ayrı satır.",
    lead: "Züccaciye vitrini. Tabak, bardak, tencere. Hırdavat değil; ev eşyası ve çeyiz. Fiyat etiketli.",
    slides: [
      { src: P.dish, alt: "Mutfak", caption: "Reyon" },
      { src: P.dish2, alt: "Tencere", caption: "Tencere" },
      { src: P.glass, alt: "Cam", caption: "Bardak" },
    ],
    services: [
      { t: "Porselen", d: "Yemek takımı." },
      { t: "Cam", d: "Bardak, sürahi." },
      { t: "Tencere", d: "Çelik / granit." },
    ],
    products: [
      { name: "Yemek takımı 24 p.", price: "₺2.450", img: P.dish, tag: "Çeyiz" },
      { name: "Tencere set 7 p.", price: "₺1.890", img: P.dish2 },
      { name: "Bardak set 6’lı", price: "₺280", img: P.glass },
      { name: "Çay bardağı 12’li", price: "₺190", img: P.glass },
    ],
    choices: ["Çeyiz listesi", "Porselen takım", "Tencere set", "Cam bardak"],
    reviews: [
      { n: "Defne çeyiz", t: "Takım stoğu sitedeki gibiydi." },
      { n: "Antakya ev", t: "Tencere kargo netti." },
    ],
    districts: ["Antakya", "Defne", "İskenderun"],
  },
  {
    slug: "hali-yikama",
    kind: "local",
    widget: "call",
    title: "Halı yıkama",
    brand: "Antakya Halı Yıkama",
    subtitle: "m² fiyat, evden alım — giysi değil",
    accent: "#0369a1",
    bg: "#0c4a6e",
    hero: P.rug,
    hook: "Halı m² sitede. Kuru temizleme değil; kilim ve yün evden alınır, kuruyunca teslim.",
    lead: "Halı yıkama sitesi. Takım / gömlek yok. Ölçü fotoğrafı, leke türü, kurutma günü yazılı.",
    slides: [
      { src: P.rug, alt: "Halı", caption: "Halı" },
      { src: P.rug2, alt: "Salon", caption: "Evden alım" },
      { src: P.house, alt: "Teslim", caption: "Teslim" },
    ],
    services: [
      { t: "m² fiyat", d: "En-boy fotoğrafla." },
      { t: "Evden alım", d: "Antakya / Defne." },
      { t: "Kurutma", d: "Gün sitede." },
    ],
    choices: ["Yün halı", "Makine halı", "Kilim", "Stor / perde"],
    reviews: [
      { n: "Defne salon", t: "m² fiyat sitedeki gibiydi." },
      { n: "Antakya", t: "Alım saati tutuldu." },
    ],
    districts: ["Antakya", "Defne", "İskenderun"],
  },
  {
    slug: "kunefe",
    kind: "local",
    widget: "menu",
    title: "Künefe",
    brand: "Antakya Künefe",
    subtitle: "Taze peynir, porsiyon fiyatı — pastane değil",
    accent: "#c2410c",
    bg: "#7c2d12",
    hero: P.dessert,
    hook: "Künefe porsiyon sitede. Yaş pasta yok; peynirli tel kadayıf, kaymak ayrı satır.",
    lead: "Künefeci vitrini. Pastane / kebap salonu değil. Porsiyon, tepsi, teslim saati yazılı.",
    slides: [
      { src: P.dessert, alt: "Tatlı", caption: "Porsiyon" },
      { src: P.cake2, alt: "Fırın", caption: "Fırın" },
      { src: P.spice, alt: "Dükkân", caption: "Tezgah" },
    ],
    services: [
      { t: "Porsiyon", d: "Anında." },
      { t: "Tepsi", d: "Saat yazılı." },
      { t: "Paket", d: "Sıcak tutucu." },
    ],
    menu: [
      { cat: "Tatlı", name: "Künefe porsiyon", price: "₺180" },
      { cat: "Tatlı", name: "Künefe kaymaklı", price: "₺220" },
      { cat: "Tatlı", name: "Tepsi (4–6 kişi)", price: "₺890" },
      { cat: "İçecek", name: "Türk kahvesi", price: "₺50" },
    ],
    choices: ["Porsiyon", "Kaymaklı", "Tepsi", "Paket"],
    reviews: [
      { n: "Defne", t: "Peynir taze, porsiyon sitedeki gibiydi." },
      { n: "Antakya", t: "Tepsi saati tutuldu." },
    ],
    districts: ["Antakya", "Defne", "Samandağ"],
  },
  {
    slug: "mobilya",
    kind: "shop",
    widget: "shop",
    title: "Mobilya",
    brand: "Antakya Mobilya",
    subtitle: "Koltuk, yatak, stok fiyatı — ölçü değil",
    accent: "#92400e",
    bg: "#451a03",
    hero: P.sofa,
    hook: "Koltuk takımı stokta. Marangoz ölçü işi değil; hazır mobilya, kargo ve montaj ayrı satır.",
    lead: "Mobilya mağazası. Mutfak dolabı siparişi yok. Kanepe, yatak, masa. Stok ve teslim günü yazılı.",
    slides: [
      { src: P.sofa, alt: "Koltuk", caption: "Koltuk" },
      { src: P.sofa2, alt: "Salon", caption: "Salon" },
      { src: P.house2, alt: "Oda", caption: "Yatak odası" },
    ],
    services: [
      { t: "Koltuk takımı", d: "3+3+1 stok." },
      { t: "Yatak", d: "Bazalı / baza yok." },
      { t: "Montaj", d: "Hatay içi ayrı." },
    ],
    products: [
      { name: "Koltuk takımı 3+3+1", price: "₺24.900", img: P.sofa, tag: "Stok" },
      { name: "Köşe koltuk", price: "₺18.500", img: P.sofa2 },
      { name: "Yatak 160x200", price: "₺9.750", img: P.house2 },
      { name: "Yemek masası 6 kişilik", price: "₺6.400", img: P.house3 },
    ],
    choices: ["Koltuk takımı", "Köşe", "Yatak", "Yemek masası"],
    reviews: [
      { n: "Defne salon", t: "Stok sitedeki gibiydi, montaj ayrı yazıldı." },
      { n: "Antakya", t: "Teslim günü tutuldu." },
    ],
    districts: ["Antakya", "Defne", "İskenderun"],
  },
  {
    slug: "ayakkabi",
    kind: "shop",
    widget: "shop",
    title: "Ayakkabı",
    brand: "Antakya Ayakkabı",
    subtitle: "Numara, stok, kargo — butik değil",
    accent: "#1d4ed8",
    bg: "#1e3a8a",
    hero: P.shoe,
    hook: "Numara sitede yazılı. Giyim butiği değil; ayakkabı ve terlik stok, iade kuralı ayrı.",
    lead: "Ayakkabı vitrini. Elbise yok. Erkek / kadın numara, kargo Hatay içi ayrı satır.",
    slides: [
      { src: P.shoe, alt: "Ayakkabı", caption: "Vitrin" },
      { src: P.shoe2, alt: "Spor", caption: "Spor" },
      { src: P.boutique2, alt: "Dükkân", caption: "Dükkân" },
    ],
    services: [
      { t: "Numara", d: "37–45 stok." },
      { t: "Iade", d: "Denemelik 7 gün." },
      { t: "Kargo", d: "Hatay içi / dışı." },
    ],
    products: [
      { name: "Spor ayakkabı", price: "₺1.890", img: P.shoe, tag: "Stok" },
      { name: "Klasik erkek", price: "₺2.450", img: P.shoe2 },
      { name: "Kadın babet", price: "₺890", img: P.boutique },
      { name: "Terlik 2’li", price: "₺420", img: P.boutique2 },
    ],
    choices: ["Spor", "Klasik", "Babet", "Terlik"],
    reviews: [
      { n: "Defne", t: "Numara sitedeki gibiydi." },
      { n: "Antakya", t: "Iade kuralı başta yazıyordu." },
    ],
    districts: ["Antakya", "Defne", "İskenderun"],
  },
];

export const EXTRA_GROUPS: { id: ExtraKind; title: string; text: string }[] = [
  { id: "local", title: "Yerel işletme siteleri", text: "Veteriner, eczane, berber, kasap, manav, künefe, spor salonu, düğün organizasyon, halı yıkama, otel, kombi — çağrı ve randevu." },
  { id: "shop", title: "E-ticaret örnekleri", text: "Kuyumcu, takı, butik, ayakkabı, zeytinyağı, züccaciye, mobilya, hırdavat, çiçekçi, optik, pet shop, motor parçası." },
  { id: "pro", title: "Kurumsal, emlak, yazılım, mobil", text: "Firma vitrini, hukuk, muhasebe, sigorta, özel yazılım ve Android / iOS." },
];

export function extraBySlug(slug: string) {
  return EXTRA_DEMOS.find((d) => d.slug === slug);
}

export function filterTools(tools: readonly { to: string; title: string; desc: string }[], query: string) {
  const term = query.trim().toLocaleLowerCase("tr-TR");
  if (!term) return [...tools];
  return tools.filter((tool) => `${tool.title} ${tool.desc} ${tool.to}`.toLocaleLowerCase("tr-TR").includes(term));
}

export function filterExtraDemos(query: string, kind: ExtraKind | "all" = "all") {
  const term = query.trim().toLocaleLowerCase("tr-TR");
  return EXTRA_DEMOS.filter((demo) => {
    if (kind !== "all" && demo.kind !== kind) return false;
    if (!term) return true;
    const haystack = [demo.title, demo.brand, demo.subtitle, demo.slug, demo.hook, ...demo.districts].join(" ").toLocaleLowerCase("tr-TR");
    return haystack.includes(term);
  });
}
